# Import Packages

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.float_format', str)

# EDA

In [2]:
df = pd.read_csv('df_combined.csv')

/var/folders/tg/g161x0m50lxgx68hfwk_3qk80000gn/T/ipykernel_25959/3424111419.py:1: DtypeWarning: Columns (12,15,30,31,32,34,35,36,38,39,40,49,52,55,58,61,64,67,86,87,88,89,90,93,94,95,96,98,105,106,107,113,145,157,169,175,181,187,193,199,205,211,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,724,725,726,728,729,730,732,733,734,736,737,738,740,741,742,744,745,746,748,749,750,752,753,754,756,757,758,760,761,762,764,765,766,768,769,770,772,773,774,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,792,793,794,795,796,797,798,799,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,921,922,923,924,925,926,927,928,929,930,931,932,933,934,935,936,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,958,959,960,961,962,963,964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,987,988,989,990,991,992,993,994,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1009,1010,1011,1012,1013,1014,1016,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070,1071,1072,1073) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('df_combined.csv')

In [3]:
df.head()

,Unnamed: 0,authorMeta/avatar,authorMeta/bioLink,authorMeta/digg,authorMeta/fans,authorMeta/following,authorMeta/friends,authorMeta/heart,authorMeta/id,authorMeta/name,authorMeta/nickName,authorMeta/originalAvatarUrl,authorMeta/privateAccount,authorMeta/profileUrl,authorMeta/signature,authorMeta/verified,authorMeta/video,collectCount,commentCount,createTime,createTimeISO,detailedMentions/0/id,detailedMentions/0/name,detailedMentions/0/nickName,detailedMentions/0/profileUrl,detailedMentions/1/id,detailedMentions/1/name,detailedMentions/1/nickName,detailedMentions/1/profileUrl,detailedMentions/2/id,detailedMentions/2/name,detailedMentions/2/nickName,detailedMentions/2/profileUrl,detailedMentions/3/id,detailedMentions/3/name,detailedMentions/3/nickName,detailedMentions/3/profileUrl,detailedMentions/4/id,detailedMentions/4/name,detailedMentions/4/nickName,detailedMentions/4/profileUrl,diggCount,effectStickers/0/ID,effectStickers/0/name,effectStickers/0/stickerStats/useCount,effectStickers/1/ID,effectStickers/1/name,effectStickers/1/stickerStats/useCount,effectStickers/2/ID,effectStickers/2/name,effectStickers/2/stickerStats/useCount,effectStickers/3/ID,effectStickers/3/name,effectStickers/3/stickerStats/useCount,effectStickers/4/ID,effectStickers/4/name,effectStickers/4/stickerStats/useCount,effectStickers/5/ID,effectStickers/5/name,effectStickers/5/stickerStats/useCount,effectStickers/6/ID,effectStickers/6/name,effectStickers/6/stickerStats/useCount,effectStickers/7/ID,effectStickers/7/name,effectStickers/7/stickerStats/useCount,effectStickers/8/ID,effectStickers/8/name,effectStickers/8/stickerStats/useCount,hashtags/0/name,hashtags/1/name,hashtags/2/name,hashtags/3/name,hashtags/4/name,hashtags/5/name,hashtags/6/name,hashtags/7/name,hashtags/8/name,hashtags/9/name,hashtags/10/name,hashtags/11/name,hashtags/12/name,hashtags/13/name,hashtags/14/name,hashtags/15/name,hashtags/16/name,hashtags/17/name,hashtags/18/name,hashtags/19/name,hashtags/20/name,hashtags/21/name,id,input,isAd,isPinned,isSlideshow,isSponsored,locationMeta/address,locationMeta/city,locationMeta/cityCode,locationMeta/countryCode,locationMeta/locationId,locationMeta/locationName,mentions/0,mentions/1,mentions/2,mentions/3,mentions/4,musicMeta/coverMediumUrl,musicMeta/musicAlbum,musicMeta/musicAuthor,musicMeta/musicId,musicMeta/musicName,musicMeta/musicOriginal,musicMeta/originalCoverMediumUrl,musicMeta/playUrl,playCount,searchHashtag/name,searchHashtag/views,shareCount,text,textLanguage,videoMeta/coverUrl,videoMeta/definition,videoMeta/duration,videoMeta/format,videoMeta/height,videoMeta/originalCoverUrl,videoMeta/subtitleLinks/0/downloadLink,videoMeta/subtitleLinks/0/language,videoMeta/subtitleLinks/0/source,videoMeta/subtitleLinks/0/sourceUnabbreviated,videoMeta/subtitleLinks/0/tiktokLink,videoMeta/subtitleLinks/0/version,videoMeta/subtitleLinks/1/downloadLink,videoMeta/subtitleLinks/1/language,videoMeta/subtitleLinks/1/source,videoMeta/subtitleLinks/1/sourceUnabbreviated,videoMeta/subtitleLinks/1/tiktokLink,videoMeta/subtitleLinks/1/version,videoMeta/subtitleLinks/2/downloadLink,videoMeta/subtitleLinks/2/language,videoMeta/subtitleLinks/2/source,videoMeta/subtitleLinks/2/sourceUnabbreviated,videoMeta/subtitleLinks/2/tiktokLink,videoMeta/subtitleLinks/2/version,videoMeta/subtitleLinks/3/downloadLink,videoMeta/subtitleLinks/3/language,videoMeta/subtitleLinks/3/source,videoMeta/subtitleLinks/3/sourceUnabbreviated,videoMeta/subtitleLinks/3/tiktokLink,videoMeta/subtitleLinks/3/version,videoMeta/subtitleLinks/4/downloadLink,videoMeta/subtitleLinks/4/language,videoMeta/subtitleLinks/4/source,videoMeta/subtitleLinks/4/sourceUnabbreviated,videoMeta/subtitleLinks/4/tiktokLink,videoMeta/subtitleLinks/4/version,videoMeta/subtitleLinks/5/downloadLink,videoMeta/subtitleLinks/5/language,videoMeta/subtitleLinks/5/source,videoMeta/subtitleLinks/5/sourceUnabbreviated,videoMeta/subtitleLinks/5/tiktokLink,videoMeta/subtitleLinks/5/version,videoMeta/subtitleLinks/6/downloadLink,videoMeta/subtitleLinks/6/language,videoMeta/subtitleLinks/6/source,videoMeta/subtitleLinks/6/sourceUnabbreviated,videoMeta/subtitleLinks/6/tiktokLink,videoMeta/subtitleLinks/6/version,videoMeta/subtitleLinks/7/downloadLink,videoMeta/subtitleLinks/7/language,videoMeta/subtitleLinks/7/source,videoMeta/subtitleLinks/7/sourceUnabbreviated,videoMeta/subtitleLinks/7/tiktokLink,videoMeta/subtitleLinks/7/version,videoMeta/subtitleLinks/8/downloadLink,videoMeta/subtitleLinks/8/language,videoMeta/subtitleLinks/8/source,videoMeta/subtitleLinks/8/sourceUnabbreviated,videoMeta/subtitleLinks/8/tiktokLink,videoMeta/subtitleLinks/8/version,videoMeta/subtitleLinks/9/downloadLink,videoMeta/subtitleLinks/9/language,videoMeta/subtitleLinks/9/source,videoMeta/subtitleLinks/9/sourceUnabbreviated,videoMeta/subtitleLinks/9/tiktokLink,videoMeta/subtitleLinks/9/version,videoMeta/subtitleLinks/10/downloadLink,videoMeta/subtitleLinks/10/language,videoMeta/subtitleLinks/10/source,videoMeta/subtitleLinks/10/sourceUnabbreviated,videoMeta/subtitleLinks/10/tiktokLink,videoMeta/subtitleLinks/10/version,videoMeta/subtitleLinks/11/downloadLink,videoMeta/subtitleLinks/11/language,videoMeta/subtitleLinks/11/source,videoMeta/subtitleLinks/11/sourceUnabbreviated,videoMeta/subtitleLinks/11/tiktokLink,videoMeta/subtitleLinks/11/version,videoMeta/subtitleLinks/12/downloadLink,videoMeta/subtitleLinks/12/language,videoMeta/subtitleLinks/12/source,videoMeta/subtitleLinks/12/sourceUnabbreviated,videoMeta/subtitleLinks/12/tiktokLink,videoMeta/subtitleLinks/12/version,videoMeta/subtitleLinks/13/downloadLink,videoMeta/subtitleLinks/13/language,videoMeta/subtitleLinks/13/source,videoMeta/subtitleLinks/13/sourceUnabbreviated,videoMeta/subtitleLinks/13/tiktokLink,videoMeta/subtitleLinks/13/version,videoMeta/subtitleLinks/14/downloadLink,videoMeta/subtitleLinks/14/language,videoMeta/subtitleLinks/14/source,videoMeta/subtitleLinks/14/sourceUnabbreviated,videoMeta/subtitleLinks/14/tiktokLink,videoMeta/subtitleLinks/14/version,videoMeta/subtitleLinks/15/downloadLink,videoMeta/subtitleLinks/15/language,videoMeta/subtitleLinks/15/source,videoMeta/subtitleLinks/15/sourceUnabbreviated,videoMeta/subtitleLinks/15/tiktokLink,videoMeta/subtitleLinks/15/version,videoMeta/subtitleLinks/16/downloadLink,videoMeta/subtitleLinks/16/language,videoMeta/subtitleLinks/16/source,videoMeta/subtitleLinks/16/sourceUnabbreviated,videoMeta/subtitleLinks/16/tiktokLink,videoMeta/subtitleLinks/16/version,videoMeta/subtitleLinks/17/downloadLink,videoMeta/subtitleLinks/17/language,videoMeta/subtitleLinks/17/source,videoMeta/subtitleLinks/17/sourceUnabbreviated,videoMeta/subtitleLinks/17/tiktokLink,videoMeta/subtitleLinks/17/version,videoMeta/subtitleLinks/18/downloadLink,videoMeta/subtitleLinks/18/language,videoMeta/subtitleLinks/18/source,videoMeta/subtitleLinks/18/sourceUnabbreviated,videoMeta/subtitleLinks/18/tiktokLink,videoMeta/subtitleLinks/18/version,videoMeta/subtitleLinks/19/downloadLink,videoMeta/subtitleLinks/19/language,videoMeta/subtitleLinks/19/source,videoMeta/subtitleLinks/19/sourceUnabbreviated,videoMeta/subtitleLinks/19/tiktokLink,videoMeta/subtitleLinks/19/version,videoMeta/subtitleLinks/20/downloadLink,videoMeta/subtitleLinks/20/language,videoMeta/subtitleLinks/20/source,videoMeta/subtitleLinks/20/sourceUnabbreviated,videoMeta/subtitleLinks/20/tiktokLink,videoMeta/subtitleLinks/20/version,videoMeta/subtitleLinks/21/downloadLink,videoMeta/subtitleLinks/21/language,videoMeta/subtitleLinks/21/source,videoMeta/subtitleLinks/21/sourceUnabbreviated,videoMeta/subtitleLinks/21/tiktokLink,videoMeta/subtitleLinks/21/version,videoMeta/subtitleLinks/22/downloadLink,videoMeta/subtitleLinks/22/language,videoMeta/subtitleLinks/22/source,videoMeta/subtitleLinks/22/sourceUnabbreviated,videoMeta/subtitleLinks/22/tiktokLink,videoMeta/subtitleLinks/22/version,videoMeta/subtitleLinks/23/downloadLink,videoMeta/subtitleLinks/23/language,videoMeta/subtitleLinks/23/source,videoMeta/subtitleLinks/23/sourceUnabbreviated,videoMeta/subtitleLinks/23/tiktokLink,videoMeta/subtitleLinks/23/version,videoMeta/subtitleLinks/24/downloadLink,videoMeta/subtitleLinks/24/language,videoMeta/subtitleLinks/24/source,videoMeta/subtitleLinks/24/sourceUnabbreviated,videoMeta/subtitleLinks/24/tiktokLink,videoMeta/subtitleLinks/24/version,videoMeta/subtitleLinks/25/downloadLink,videoMeta/subtitleLinks/25/language,videoMeta/subtitleLinks/25/source,videoMeta/subtitleLinks/25/sourceUnabbreviated,videoMeta/subtitleLinks/25/tiktokLink,videoMeta/subtitleLinks/25/version,videoMeta/subtitleLinks/26/downloadLink,videoMeta/subtitleLinks/26/language,videoMeta/subtitleLinks/26/source,videoMeta/subtitleLinks/26/sourceUnabbreviated,videoMeta/subtitleLinks/26/tiktokLink,videoMeta/subtitleLinks/26/version,videoMeta/subtitleLinks/27/downloadLink,videoMeta/subtitleLinks/27/language,videoMeta/subtitleLinks/27/source,videoMeta/subtitleLinks/27/sourceUnabbreviated,videoMeta/subtitleLinks/27/tiktokLink,videoMeta/subtitleLinks/27/version,videoMeta/subtitleLinks/28/downloadLink,videoMeta/subtitleLinks/28/language,videoMeta/subtitleLinks/28/source,videoMeta/subtitleLinks/28/sourceUnabbreviated,videoMeta/subtitleLinks/28/tiktokLink,videoMeta/subtitleLinks/28/version,videoMeta/subtitleLinks/29/downloadLink,videoMeta/subtitleLinks/29/language,videoMeta/subtitleLinks/29/source,videoMeta/subtitleLinks/29/sourceUnabbreviated,videoMeta/subtitleLinks/29/tiktokLink,videoMeta/subtitleLinks/29/version,videoMeta/subtitleLinks/30/downloadLink,videoMeta/subtitleLinks/30/language,videoMeta/subtitleLinks/30/source,videoMeta/subtitleLinks/30/sourceUnabbreviated,videoMeta/subtitleLinks/30/tiktokLink,videoMeta/subtitleLinks/30/version,videoMeta/subtitleLinks/31/downloadLink,videoMeta/subtitleLinks/31/language,videoMeta/subtitleLinks/31/source,videoMeta/subtitleLinks/31/sourceUnabbreviated,videoMeta/subtitleLinks/31/tiktokLink,videoMeta/subtitleLinks/31/version,videoMeta/subtitleLinks/32/downloadLink,videoMeta/subtitleLinks/32/language,videoMeta/subtitleLinks/32/source,videoMeta/subtitleLinks/32/sourceUnabbreviated,videoMeta/subtitleLinks/32/tiktokLink,videoMeta/subtitleLinks/32/version,videoMeta/subtitleLinks/33/downloadLink,videoMeta/subtitleLinks/33/language,videoMeta/subtitleLinks/33/source,videoMeta/subtitleLinks/33/sourceUnabbreviated,videoMeta/subtitleLinks/33/tiktokLink,videoMeta/subtitleLinks/33/version,videoMeta/subtitleLinks/34/downloadLink,videoMeta/subtitleLinks/34/language,videoMeta/subtitleLinks/34/source,videoMeta/subtitleLinks/34/sourceUnabbreviated,videoMeta/subtitleLinks/34/tiktokLink,videoMeta/subtitleLinks/34/version,videoMeta/subtitleLinks/35/downloadLink,videoMeta/subtitleLinks/35/language,videoMeta/subtitleLinks/35/source,videoMeta/subtitleLinks/35/sourceUnabbreviated,videoMeta/subtitleLinks/35/tiktokLink,videoMeta/subtitleLinks/35/version,videoMeta/subtitleLinks/36/downloadLink,videoMeta/subtitleLinks/36/language,videoMeta/subtitleLinks/36/source,videoMeta/subtitleLinks/36/sourceUnabbreviated,videoMeta/subtitleLinks/36/tiktokLink,videoMeta/subtitleLinks/36/version,videoMeta/subtitleLinks/37/downloadLink,videoMeta/subtitleLinks/37/language,videoMeta/subtitleLinks/37/source,videoMeta/subtitleLinks/37/sourceUnabbreviated,videoMeta/subtitleLinks/37/tiktokLink,videoMeta/subtitleLinks/37/version,videoMeta/subtitleLinks/38/downloadLink,videoMeta/subtitleLinks/38/language,videoMeta/subtitleLinks/38/source,videoMeta/subtitleLinks/38/sourceUnabbreviated,videoMeta/subtitleLinks/38/tiktokLink,videoMeta/subtitleLinks/38/version,videoMeta/subtitleLinks/39/downloadLink,videoMeta/subtitleLinks/39/language,videoMeta/subtitleLinks/39/source,videoMeta/subtitleLinks/39/sourceUnabbreviated,videoMeta/subtitleLinks/39/tiktokLink,videoMeta/subtitleLinks/39/version,videoMeta/subtitleLinks/40/downloadLink,videoMeta/subtitleLinks/40/language,videoMeta/subtitleLinks/40/source,videoMeta/subtitleLinks/40/sourceUnabbreviated,videoMeta/subtitleLinks/40/tiktokLink,videoMeta/subtitleLinks/40/version,videoMeta/subtitleLinks/41/downloadLink,videoMeta/subtitleLinks/41/language,videoMeta/subtitleLinks/41/source,videoMeta/subtitleLinks/41/sourceUnabbreviated,videoMeta/subtitleLinks/41/tiktokLink,videoMeta/subtitleLinks/41/version,videoMeta/subtitleLinks/42/downloadLink,videoMeta/subtitleLinks/42/language,videoMeta/subtitleLinks/42/source,videoMeta/subtitleLinks/42/sourceUnabbreviated,videoMeta/subtitleLinks/42/tiktokLink,videoMeta/subtitleLinks/42/version,videoMeta/subtitleLinks/43/downloadLink,videoMeta/subtitleLinks/43/language,videoMeta/subtitleLinks/43/source,videoMeta/subtitleLinks/43/sourceUnabbreviated,videoMeta/subtitleLinks/43/tiktokLink,videoMeta/subtitleLinks/43/version,videoMeta/subtitleLinks/44/downloadLink,videoMeta/subtitleLinks/44/language,videoMeta/subtitleLinks/44/source,videoMeta/subtitleLinks/44/sourceUnabbreviated,videoMeta/subtitleLinks/44/tiktokLink,videoMeta/subtitleLinks/44/version,videoMeta/subtitleLinks/45/downloadLink,videoMeta/subtitleLinks/45/language,videoMeta/subtitleLinks/45/source,videoMeta/subtitleLinks/45/sourceUnabbreviated,videoMeta/subtitleLinks/45/tiktokLink,videoMeta/subtitleLinks/45/version,videoMeta/subtitleLinks/46/downloadLink,videoMeta/subtitleLinks/46/language,videoMeta/subtitleLinks/46/source,videoMeta/subtitleLinks/46/sourceUnabbreviated,videoMeta/subtitleLinks/46/tiktokLink,videoMeta/subtitleLinks/46/version,videoMeta/subtitleLinks/47/downloadLink,videoMeta/subtitleLinks/47/language,videoMeta/subtitleLinks/47/source,videoMeta/subtitleLinks/47/sourceUnabbreviated,videoMeta/subtitleLinks/47/tiktokLink,videoMeta/subtitleLinks/47/version,videoMeta/subtitleLinks/48/downloadLink,videoMeta/subtitleLinks/48/language,videoMeta/subtitleLinks/48/source,videoMeta/subtitleLinks/48/sourceUnabbreviated,videoMeta/subtitleLinks/48/tiktokLink,videoMeta/subtitleLinks/48/version,videoMeta/subtitleLinks/49/downloadLink,videoMeta/subtitleLinks/49/language,videoMeta/subtitleLinks/49/source,videoMeta/subtitleLinks/49/sourceUnabbreviated,videoMeta/subtitleLinks/49/tiktokLink,videoMeta/subtitleLinks/49/version,videoMeta/subtitleLinks/50/downloadLink,videoMeta/subtitleLinks/50/language,videoMeta/subtitleLinks/50/source,videoMeta/subtitleLinks/50/sourceUnabbreviated,videoMeta/subtitleLinks/50/tiktokLink,videoMeta/subtitleLinks/50/version,videoMeta/subtitleLinks/51/downloadLink,videoMeta/subtitleLinks/51/language,videoMeta/subtitleLinks/51/source,videoMeta/subtitleLinks/51/sourceUnabbreviated,videoMeta/subtitleLinks/51/tiktokLink,videoMeta/subtitleLinks/51/version,videoMeta/subtitleLinks/52/downloadLink,videoMeta/subtitleLinks/52/language,videoMeta/subtitleLinks/52/source,videoMeta/subtitleLinks/52/sourceUnabbreviated,videoMeta/subtitleLinks/52/tiktokLink,videoMeta/subtitleLinks/52/version,videoMeta/subtitleLinks/53/downloadLink,videoMeta/subtitleLinks/53/language,videoMeta/subtitleLinks/53/source,videoMeta/subtitleLinks/53/sourceUnabbreviated,videoMeta/subtitleLinks/53/tiktokLink,videoMeta/subtitleLinks/53/version,videoMeta/subtitleLinks/54/downloadLink,videoMeta/subtitleLinks/54/language,videoMeta/subtitleLinks/54/source,videoMeta/subtitleLinks/54/sourceUnabbreviated,videoMeta/subtitleLinks/54/tiktokLink,videoMeta/subtitleLinks/54/version,videoMeta/subtitleLinks/55/downloadLink,videoMeta/subtitleLinks/55/language,videoMeta/subtitleLinks/55/source,videoMeta/subtitleLinks/55/sourceUnabbreviated,videoMeta/subtitleLinks/55/tiktokLink,videoMeta/subtitleLinks/55/version,videoMeta/subtitleLinks/56/downloadLink,videoMeta/subtitleLinks/56/language,videoMeta/subtitleLinks/56/source,videoMeta/subtitleLinks/56/sourceUnabbreviated,videoMeta/subtitleLinks/56/tiktokLink,videoMeta/subtitleLinks/56/version,videoMeta/subtitleLinks/57/downloadLink,videoMeta/subtitleLinks/57/language,videoMeta/subtitleLinks/57/source,videoMeta/subtitleLinks/57/sourceUnabbreviated,videoMeta/subtitleLinks/57/tiktokLink,videoMeta/subtitleLinks/57/version,videoMeta/subtitleLinks/58/downloadLink,videoMeta/subtitleLinks/58/language,videoMeta/subtitleLinks/58/source,videoMeta/subtitleLinks/58/sourceUnabbreviated,videoMeta/subtitleLinks/58/tiktokLink,videoMeta/subtitleLinks/58/version,videoMeta/subtitleLinks/59/downloadLink,videoMeta/subtitleLinks/59/language,videoMeta/subtitleLinks/59/source,videoMeta/subtitleLinks/59/sourceUnabbreviated,videoMeta/subtitleLinks/59/tiktokLink,videoMeta/subtitleLinks/59/version,videoMeta/subtitleLinks/60/downloadLink,videoMeta/subtitleLinks/60/language,videoMeta/subtitleLinks/60/source,videoMeta/subtitleLinks/60/sourceUnabbreviated,videoMeta/subtitleLinks/60/tiktokLink,videoMeta/subtitleLinks/60/version,videoMeta/subtitleLinks/61/downloadLink,videoMeta/subtitleLinks/61/language,videoMeta/subtitleLinks/61/source,videoMeta/subtitleLinks/61/sourceUnabbreviated,videoMeta/subtitleLinks/61/tiktokLink,videoMeta/subtitleLinks/61/version,videoMeta/subtitleLinks/62/downloadLink,videoMeta/subtitleLinks/62/language,videoMeta/subtitleLinks/62/source,videoMeta/subtitleLinks/62/sourceUnabbreviated,videoMeta/subtitleLinks/62/tiktokLink,videoMeta/subtitleLinks/62/version,videoMeta/width,webVideoUrl,detailedMentions/0/postUrl,videoMeta/subtitleLinks/63/downloadLink,videoMeta/subtitleLinks/63/language,videoMeta/subtitleLinks/63/source,videoMeta/subtitleLinks/63/sourceUnabbreviated,videoMeta/subtitleLinks/63/tiktokLink,videoMeta/subtitleLinks/63/version,videoMeta/subtitleLinks/64/downloadLink,videoMeta/subtitleLinks/64/language,videoMeta/subtitleLinks/64/source,videoMeta/subtitleLinks/64/sourceUnabbreviated,videoMeta/subtitleLinks/64/tiktokLink,videoMeta/subtitleLinks/64/version,videoMeta/subtitleLinks/65/downloadLink,videoMeta/subtitleLinks/65/language,videoMeta/subtitleLinks/65/source,videoMeta/subtitleLinks/65/sourceUnabbreviated,videoMeta/subtitleLinks/65/tiktokLink,videoMeta/subtitleLinks/65/version,videoMeta/subtitleLinks/66/downloadLink,videoMeta/subtitleLinks/66/language,videoMeta/subtitleLinks/66/source,videoMeta/subtitleLinks/66/sourceUnabbreviated,videoMeta/subtitleLinks/66/tiktokLink,videoMeta/subtitleLinks/66/version,videoMeta/subtitleLinks/67/downloadLink,videoMeta/subtitleLinks/67/language,videoMeta/subtitleLinks/67/source,videoMeta/subtitleLinks/67/sourceUnabbreviated,videoMeta/subtitleLinks/67/tiktokLink,videoMeta/subtitleLinks/67/version,videoMeta/subtitleLinks/68/downloadLink,videoMeta/subtitleLinks/68/language,videoMeta/subtitleLinks/68/source,videoMeta/subtitleLinks/68/sourceUnabbreviated,videoMeta/subtitleLinks/68/tiktokLink,videoMeta/subtitleLinks/68/version,videoMeta/subtitleLinks/69/downloadLink,videoMeta/subtitleLinks/69/language,videoMeta/subtitleLinks/69/source,videoMeta/subtitleLinks/69/sourceUnabbreviated,videoMeta/subtitleLinks/69/tiktokLink,videoMeta/subtitleLinks/69/version,videoMeta/subtitleLinks/70/downloadLink,videoMeta/subtitleLinks/70/language,videoMeta/subtitleLinks/70/source,videoMeta/subtitleLinks/70/sourceUnabbreviated,videoMeta/subtitleLinks/70/tiktokLink,videoMeta/subtitleLinks/70/version,videoMeta/subtitleLinks/71/downloadLink,videoMeta/subtitleLinks/71/language,videoMeta/subtitleLinks/71/source,videoMeta/subtitleLinks/71/sourceUnabbreviated,videoMeta/subtitleLinks/71/tiktokLink,videoMeta/subtitleLinks/71/version,videoMeta/subtitleLinks/72/downloadLink,videoMeta/subtitleLinks/72/language,videoMeta/subtitleLinks/72/source,videoMeta/subtitleLinks/72/sourceUnabbreviated,videoMeta/subtitleLinks/72/tiktokLink,videoMeta/subtitleLinks/72/version,videoMeta/subtitleLinks/73/downloadLink,videoMeta/subtitleLinks/73/language,videoMeta/subtitleLinks/73/source,videoMeta/subtitleLinks/73/sourceUnabbreviated,videoMeta/subtitleLinks/73/tiktokLink,videoMeta/subtitleLinks/73/version,videoMeta/subtitleLinks/74/downloadLink,videoMeta/subtitleLinks/74/language,videoMeta/subtitleLinks/74/source,videoMeta/subtitleLinks/74/sourceUnabbreviated,videoMeta/subtitleLinks/74/tiktokLink,videoMeta/subtitleLinks/74/version,videoMeta/subtitleLinks/75/downloadLink,videoMeta/subtitleLinks/75/language,videoMeta/subtitleLinks/75/source,videoMeta/subtitleLinks/75/sour

In [4]:
df.shape

(9232, 1074)

In [5]:
df.columns.tolist()

['Unnamed: 0',
 'authorMeta/avatar',
 'authorMeta/bioLink',
 'authorMeta/digg',
 'authorMeta/fans',
 'authorMeta/following',
 'authorMeta/friends',
 'authorMeta/heart',
 'authorMeta/id',
 'authorMeta/name',
 'authorMeta/nickName',
 'authorMeta/originalAvatarUrl',
 'authorMeta/privateAccount',
 'authorMeta/profileUrl',
 'authorMeta/signature',
 'authorMeta/verified',
 'authorMeta/video',
 'collectCount',
 'commentCount',
 'createTime',
 'createTimeISO',
 'detailedMentions/0/id',
 'detailedMentions/0/name',
 'detailedMentions/0/nickName',
 'detailedMentions/0/profileUrl',
 'detailedMentions/1/id',
 'detailedMentions/1/name',
 'detailedMentions/1/nickName',
 'detailedMentions/1/profileUrl',
 'detailedMentions/2/id',
 'detailedMentions/2/name',
 'detailedMentions/2/nickName',
 'detailedMentions/2/profileUrl',
 'detailedMentions/3/id',
 'detailedMentions/3/name',
 'detailedMentions/3/nickName',
 'detailedMentions/3/profileUrl',
 'detailedMentions/4/id',
 'detailedMentions/4/name',
 'detailedMentions/4/nickName',
 'detailedMentions/4/profileUrl',
 'diggCount',
 'effectStickers/0/ID',
 'effectStickers/0/name',
 'effectStickers/0/stickerStats/useCount',
 'effectStickers/1/ID',
 'effectStickers/1/name',
 'effectStickers/1/stickerStats/useCount',
 'effectStickers/2/ID',
 'effectStickers/2/name',
 'effectStickers/2/stickerStats/useCount',
 'effectStickers/3/ID',
 'effectStickers/3/name',
 'effectStickers/3/stickerStats/useCount',
 'effectStickers/4/ID',
 'effectStickers/4/name',
 'effectStickers/4/stickerStats/useCount',
 'effectStickers/5/ID',
 'effectStickers/5/name',
 'effectStickers/5/stickerStats/useCount',
 'effectStickers/6/ID',
 'effectStickers/6/name',
 'effectStickers/6/stickerStats/useCount',
 'effectStickers/7/ID',
 'effectStickers/7/name',
 'effectStickers/7/stickerStats/useCount',
 'effectStickers/8/ID',
 'effectStickers/8/name',
 'effectStickers/8/stickerStats/useCount',
 'hashtags/0/name',
 'hashtags/1/name',
 'hashtags/2/name',
 'hashtags/3/name',
 'hashtags/4/name',
 'hashtags/5/name',
 'hashtags/6/name',
 'hashtags/7/name',
 'hashtags/8/name',
 'hashtags/9/name',
 'hashtags/10/name',
 'hashtags/11/name',
 'hashtags/12/name',
 'hashtags/13/name',
 'hashtags/14/name',
 'hashtags/15/name',
 'hashtags/16/name',
 'hashtags/17/name',
 'hashtags/18/name',
 'hashtags/19/name',
 'hashtags/20/name',
 'hashtags/21/name',
 'id',
 'input',
 'isAd',
 'isPinned',
 'isSlideshow',
 'isSponsored',
 'locationMeta/address',
 'locationMeta/city',
 'locationMeta/cityCode',
 'locationMeta/countryCode',
 'locationMeta/locationId',
 'locationMeta/locationName',
 'mentions/0',
 'mentions/1',
 'mentions/2',
 'mentions/3',
 'mentions/4',
 'musicMeta/coverMediumUrl',
 'musicMeta/musicAlbum',
 'musicMeta/musicAuthor',
 'musicMeta/musicId',
 'musicMeta/musicName',
 'musicMeta/musicOriginal',
 'musicMeta/originalCoverMediumUrl',
 'musicMeta/playUrl',
 'playCount',
 'searchHashtag/name',
 'searchHashtag/views',
 'shareCount',
 'text',
 'textLanguage',
 'videoMeta/coverUrl',
 'videoMeta/definition',
 'videoMeta/duration',
 'videoMeta/format',
 'videoMeta/height',
 'videoMeta/originalCoverUrl',
 'videoMeta/subtitleLinks/0/downloadLink',
 'videoMeta/subtitleLinks/0/language',
 'videoMeta/subtitleLinks/0/source',
 'videoMeta/subtitleLinks/0/sourceUnabbreviated',
 'videoMeta/subtitleLinks/0/tiktokLink',
 'videoMeta/subtitleLinks/0/version',
 'videoMeta/subtitleLinks/1/downloadLink',
 'videoMeta/subtitleLinks/1/language',
 'videoMeta/subtitleLinks/1/source',
 'videoMeta/subtitleLinks/1/sourceUnabbreviated',
 'videoMeta/subtitleLinks/1/tiktokLink',
 'videoMeta/subtitleLinks/1/version',
 'videoMeta/subtitleLinks/2/downloadLink',
 'videoMeta/subtitleLinks/2/language',
 'videoMeta/subtitleLinks/2/source',
 'videoMeta/subtitleLinks/2/sourceUnabbreviated',
 'videoMeta/subtitleLinks/2/tiktokLink',
 'videoMeta/subtitleLinks/2/version',
 'videoMeta/subtitleLinks/3/downloadLink',
 'videoMeta/subtitleLinks/3/language',
 'videoMeta/subtitleLinks/3/source',
 'videoMeta/subtitleLinks/3/sourceUnabbreviated',
 'videoMeta/subtitleLinks/3/tiktokLink',
 'videoMeta/subtitleLinks/3/version',
 'videoMeta/subtitleLinks/4/downloadLink',
 'videoMeta/subtitleLinks/4/language',
 'videoMeta/subtitleLinks/4/source',
 'videoMeta/subtitleLinks/4/sourceUnabbreviated',
 'videoMeta/subtitleLinks/4/tiktokLink',
 'videoMeta/subtitleLinks/4/version',
 'videoMeta/subtitleLinks/5/downloadLink',
 'videoMeta/subtitleLinks/5/language',
 'videoMeta/subtitleLinks/5/source',
 'videoMeta/subtitleLinks/5/sourceUnabbreviated',
 'videoMeta/subtitleLinks/5/tiktokLink',
 'videoMeta/subtitleLinks/5/version',
 'videoMeta/subtitleLinks/6/downloadLink',
 'videoMeta/subtitleLinks/6/language',
 'videoMeta/subtitleLinks/6/source',
 'videoMeta/subtitleLinks/6/sourceUnabbreviated',
 'videoMeta/subtitleLinks/6/tiktokLink',
 'videoMeta/subtitleLinks/6/version',
 'videoMeta/subtitleLinks/7/downloadLink',
 'videoMeta/subtitleLinks/7/language',
 'videoMeta/subtitleLinks/7/source',
 'videoMeta/subtitleLinks/7/sourceUnabbreviated',
 'videoMeta/subtitleLinks/7/tiktokLink',
 'videoMeta/subtitleLinks/7/version',
 'videoMeta/subtitleLinks/8/downloadLink',
 'videoMeta/subtitleLinks/8/language',
 'videoMeta/subtitleLinks/8/source',
 'videoMeta/subtitleLinks/8/sourceUnabbreviated',
 'videoMeta/subtitleLinks/8/tiktokLink',
 'videoMeta/subtitleLinks/8/version',
 'videoMeta/subtitleLinks/9/downloadLink',
 'videoMeta/subtitleLinks/9/language',
 'videoMeta/subtitleLinks/9/source',
 'videoMeta/subtitleLinks/9/sourceUnabbreviated',
 'videoMeta/subtitleLinks/9/tiktokLink',
 'videoMeta/subtitleLinks/9/version',
 'videoMeta/subtitleLinks/10/downloadLink',
 'videoMeta/subtitleLinks/10/language',
 'videoMeta/subtitleLinks/10/source',
 'videoMeta/subtitleLinks/10/sourceUnabbreviated',
 'videoMeta/subtitleLinks/10/tiktokLink',
 'videoMeta/subtitleLinks/10/version',
 'videoMeta/subtitleLinks/11/downloadLink',
 'videoMeta/subtitleLinks/11/language',
 'videoMeta/subtitleLinks/11/source',
 'videoMeta/subtitleLinks/11/sourceUnabbreviated',
 'videoMeta/subtitleLinks/11/tiktokLink',
 'videoMeta/subtitleLinks/11/version',
 'videoMeta/subtitleLinks/12/downloadLink',
 'videoMeta/subtitleLinks/12/language',
 'videoMeta/subtitleLinks/12/source',
 'videoMeta/subtitleLinks/12/sourceUnabbreviated',
 'videoMeta/subtitleLinks/12/tiktokLink',
 'videoMeta/subtitleLinks/12/version',
 'videoMeta/subtitleLinks/13/downloadLink',
 'videoMeta/subtitleLinks/13/language',
 'videoMeta/subtitleLinks/13/source',
 'videoMeta/subtitleLinks/13/sourceUnabbreviated',
 'videoMeta/subtitleLinks/13/tiktokLink',
 'videoMeta/subtitleLinks/13/version',
 'videoMeta/subtitleLinks/14/downloadLink',
 'videoMeta/subtitleLinks/14/language',
 'videoMeta/subtitleLinks/14/source',
 'videoMeta/subtitleLinks/14/sourceUnabbreviated',
 'videoMeta/subtitleLinks/14/tiktokLink',
 'videoMeta/subtitleLinks/14/version',
 'videoMeta/subtitleLinks/15/downloadLink',
 'videoMeta/subtitleLinks/15/language',
 'videoMeta/subtitleLinks/15/source',
 'videoMeta/subtitleLinks/15/sourceUnabbreviated',
 'videoMeta/subtitleLinks/15/tiktokLink',
 'videoMeta/subtitleLinks/15/version',
 'videoMeta/subtitleLinks/16/downloadLink',
 'videoMeta/subtitleLinks/16/language',
 'videoMeta/subtitleLinks/16/source',
 'videoMeta/subtitleLinks/16/sourceUnabbreviated',
 'videoMeta/subtitleLinks/16/tiktokLink',
 'videoMeta/subtitleLinks/16/version',
 'videoMeta/subtitleLinks/17/downloadLink',
 'videoMeta/subtitleLinks/17/language',
 'videoMeta/subtitleLinks/17/source',
 'videoMeta/subtitleLinks/17/sourceUnabbreviated',
 'videoMeta/subtitleLinks/17/tiktokLink',
 'videoMeta/subtitleLinks/17/version',
 'videoMeta/subtitleLinks/18/downloadLink',
 'videoMeta/subtitleLinks/18/language',
 'videoMeta/subtitleLinks/18/source',
 'videoMeta/subtitleLinks/18/sourceUnabbreviated',
 'videoMeta/subtitleLinks/18/tiktokLink',
 'videoMeta/subtitleLinks/18/version',
 'videoMeta/subtitleLinks/19/downloadLink',
 'videoMeta/subtitleLinks/19/language',
 'videoMeta/subtitleLinks/19/source',
 'videoMeta/subtitleLinks/19/sourceUnabbreviated',
 'videoMeta/subtitleLinks/19/tiktokLink',
 'videoMeta/subtitleLinks/19/version',
 'videoMeta/subtitleLinks/20/downloadLink',
 'videoMeta/subtitleLinks/20/language',
 'videoMeta/subtitleLinks/20/source',
 'videoMeta/subtitleLinks/20/sourceUnabbreviated',
 'videoMeta/subtitleLinks/20/tiktokLink',
 'videoMeta/subtitleLinks/20/version',
 'videoMeta/subtitleLinks/21/downloadLink',
 'videoMeta/subtitleLinks/21/language',
 'videoMeta/subtitleLinks/21/source',
 'videoMeta/subtitleLinks/21/sourceUnabbreviated',
 'videoMeta/subtitleLinks/21/tiktokLink',
 'videoMeta/subtitleLinks/21/version',
 'videoMeta/subtitleLinks/22/downloadLink',
 'videoMeta/subtitleLinks/22/language',
 'videoMeta/subtitleLinks/22/source',
 'videoMeta/subtitleLinks/22/sourceUnabbreviated',
 'videoMeta/subtitleLinks/22/tiktokLink',
 'videoMeta/subtitleLinks/22/version',
 'videoMeta/subtitleLinks/23/downloadLink',
 'videoMeta/subtitleLinks/23/language',
 'videoMeta/subtitleLinks/23/source',
 'videoMeta/subtitleLinks/23/sourceUnabbreviated',
 'videoMeta/subtitleLinks/23/tiktokLink',
 'videoMeta/subtitleLinks/23/version',
 'videoMeta/subtitleLinks/24/downloadLink',
 'videoMeta/subtitleLinks/24/language',
 'videoMeta/subtitleLinks/24/source',
 'videoMeta/subtitleLinks/24/sourceUnabbreviated',
 'videoMeta/subtitleLinks/24/tiktokLink',
 'videoMeta/subtitleLinks/24/version',
 'videoMeta/subtitleLinks/25/downloadLink',
 'videoMeta/subtitleLinks/25/language',
 'videoMeta/subtitleLinks/25/source',
 'videoMeta/subtitleLinks/25/sourceUnabbreviated',
 'videoMeta/subtitleLinks/25/tiktokLink',
 'videoMeta/subtitleLinks/25/version',
 'videoMeta/subtitleLinks/26/downloadLink',
 'videoMeta/subtitleLinks/26/language',
 'videoMeta/subtitleLinks/26/source',
 'videoMeta/subtitleLinks/26/sourceUnabbreviated',
 'videoMeta/subtitleLinks/26/tiktokLink',
 'videoMeta/subtitleLinks/26/version',
 'videoMeta/subtitleLinks/27/downloadLink',
 'videoMeta/subtitleLinks/27/language',
 'videoMeta/subtitleLinks/27/source',
 'videoMeta/subtitleLinks/27/sourceUnabbreviated',
 'videoMeta/subtitleLinks/27/tiktokLink',
 'videoMeta/subtitleLinks/27/version',
 'videoMeta/subtitleLinks/28/downloadLink',
 'videoMeta/subtitleLinks/28/language',
 'videoMeta/subtitleLinks/28/source',
 'videoMeta/subtitleLinks/28/sourceUnabbreviated',
 'videoMeta/subtitleLinks/28/tiktokLink',
 'videoMeta/subtitleLinks/28/version',
 'videoMeta/subtitleLinks/29/downloadLink',
 'videoMeta/subtitleLinks/29/language',
 'videoMeta/subtitleLinks/29/source',
 'videoMeta/subtitleLinks/29/sourceUnabbreviated',
 'videoMeta/subtitleLinks/29/tiktokLink',
 'videoMeta/subtitleLinks/29/version',
 'videoMeta/subtitleLinks/30/downloadLink',
 'videoMeta/subtitleLinks/30/language',
 'videoMeta/subtitleLinks/30/source',
 'videoMeta/subtitleLinks/30/sourceUnabbreviated',
 'videoMeta/subtitleLinks/30/tiktokLink',
 'videoMeta/subtitleLinks/30/version',
 'videoMeta/subtitleLinks/31/downloadLink',
 'videoMeta/subtitleLinks/31/language',
 'videoMeta/subtitleLinks/31/source',
 'videoMeta/subtitleLinks/31/sourceUnabbreviated',
 'videoMeta/subtitleLinks/31/tiktokLink',
 'videoMeta/subtitleLinks/31/version',
 'videoMeta/subtitleLinks/32/downloadLink',
 'videoMeta/subtitleLinks/32/language',
 'videoMeta/subtitleLinks/32/source',
 'videoMeta/subtitleLinks/32/sourceUnabbreviated',
 'videoMeta/subtitleLinks/32/tiktokLink',
 'videoMeta/subtitleLinks/32/version',
 'videoMeta/subtitleLinks/33/downloadLink',
 'videoMeta/subtitleLinks/33/language',
 'videoMeta/subtitleLinks/33/source',
 'videoMeta/subtitleLinks/33/sourceUnabbreviated',
 'videoMeta/subtitleLinks/33/tiktokLink',
 'videoMeta/subtitleLinks/33/version',
 'videoMeta/subtitleLinks/34/downloadLink',
 'videoMeta/subtitleLinks/34/language',
 'videoMeta/subtitleLinks/34/source',
 'videoMeta/subtitleLinks/34/sourceUnabbreviated',
 'videoMeta/subtitleLinks/34/tiktokLink',
 'videoMeta/subtitleLinks/34/version',
 'videoMeta/subtitleLinks/35/downloadLink',
 'videoMeta/subtitleLinks/35/language',
 'videoMeta/subtitleLinks/35/source',
 'videoMeta/subtitleLinks/35/sourceUnabbreviated',
 'videoMeta/subtitleLinks/35/tiktokLink',
 'videoMeta/subtitleLinks/35/version',
 'videoMeta/subtitleLinks/36/downloadLink',
 'videoMeta/subtitleLinks/36/language',
 'videoMeta/subtitleLinks/36/source',
 'videoMeta/subtitleLinks/36/sourceUnabbreviated',
 'videoMeta/subtitleLinks/36/tiktokLink',
 'videoMeta/subtitleLinks/36/version',
 'videoMeta/subtitleLinks/37/downloadLink',
 'videoMeta/subtitleLinks/37/language',
 'videoMeta/subtitleLinks/37/source',
 'videoMeta/subtitleLinks/37/sourceUnabbreviated',
 'videoMeta/subtitleLinks/37/tiktokLink',
 'videoMeta/subtitleLinks/37/version',
 'videoMeta/subtitleLinks/38/downloadLink',
 'videoMeta/subtitleLinks/38/language',
 'videoMeta/subtitleLinks/38/source',
 'videoMeta/subtitleLinks/38/sourceUnabbreviated',
 'videoMeta/subtitleLinks/38/tiktokLink',
 'videoMeta/subtitleLinks/38/version',
 'videoMeta/subtitleLinks/39/downloadLink',
 'videoMeta/subtitleLinks/39/language',
 'videoMeta/subtitleLinks/39/source',
 'videoMeta/subtitleLinks/39/sourceUnabbreviated',
 'videoMeta/subtitleLinks/39/tiktokLink',
 'videoMeta/subtitleLinks/39/version',
 'videoMeta/subtitleLinks/40/downloadLink',
 'videoMeta/subtitleLinks/40/language',
 'videoMeta/subtitleLinks/40/source',
 'videoMeta/subtitleLinks/40/sourceUnabbreviated',
 'videoMeta/subtitleLinks/40/tiktokLink',
 'videoMeta/subtitleLinks/40/version',
 'videoMeta/subtitleLinks/41/downloadLink',
 'videoMeta/subtitleLinks/41/language',
 'videoMeta/subtitleLinks/41/source',
 'videoMeta/subtitleLinks/41/sourceUnabbreviated',
 'videoMeta/subtitleLinks/41/tiktokLink',
 'videoMeta/subtitleLinks/41/version',
 'videoMeta/subtitleLinks/42/downloadLink',
 'videoMeta/subtitleLinks/42/language',
 'videoMeta/subtitleLinks/42/source',
 'videoMeta/subtitleLinks/42/sourceUnabbreviated',
 'videoMeta/subtitleLinks/42/tiktokLink',
 'videoMeta/subtitleLinks/42/version',
 'videoMeta/subtitleLinks/43/downloadLink',
 'videoMeta/subtitleLinks/43/language',
 'videoMeta/subtitleLinks/43/source',
 'videoMeta/subtitleLinks/43/sourceUnabbreviated',
 'videoMeta/subtitleLinks/43/tiktokLink',
 'videoMeta/subtitleLinks/43/version',
 'videoMeta/subtitleLinks/44/downloadLink',
 'videoMeta/subtitleLinks/44/language',
 'videoMeta/subtitleLinks/44/source',
 'videoMeta/subtitleLinks/44/sourceUnabbreviated',
 'videoMeta/subtitleLinks/44/tiktokLink',
 'videoMeta/subtitleLinks/44/version',
 'videoMeta/subtitleLinks/45/downloadLink',
 'videoMeta/subtitleLinks/45/language',
 'videoMeta/subtitleLinks/45/source',
 'videoMeta/subtitleLinks/45/sourceUnabbreviated',
 'videoMeta/subtitleLinks/45/tiktokLink',
 'videoMeta/subtitleLinks/45/version',
 'videoMeta/subtitleLinks/46/downloadLink',
 'videoMeta/subtitleLinks/46/language',
 'videoMeta/subtitleLinks/46/source',
 'videoMeta/subtitleLinks/46/sourceUnabbreviated',
 'videoMeta/subtitleLinks/46/tiktokLink',
 'videoMeta/subtitleLinks/46/version',
 'videoMeta/subtitleLinks/47/downloadLink',
 'videoMeta/subtitleLinks/47/language',
 'videoMeta/subtitleLinks/47/source',
 'videoMeta/subtitleLinks/47/sourceUnabbreviated',
 'videoMeta/subtitleLinks/47/tiktokLink',
 'videoMeta/subtitleLinks/47/version',
 'videoMeta/subtitleLinks/48/downloadLink',
 'videoMeta/subtitleLinks/48/language',
 'videoMeta/subtitleLinks/48/source',
 'videoMeta/subtitleLinks/48/sourceUnabbreviated',
 'videoMeta/subtitleLinks/48/tiktokLink',
 'videoMeta/subtitleLinks/48/version',
 'videoMeta/subtitleLinks/49/downloadLink',
 'videoMeta/subtitleLinks/49/language',
 'videoMeta/subtitleLinks/49/source',
 'videoMeta/subtitleLinks/49/sourceUnabbreviated',
 'videoMeta/subtitleLinks/49/tiktokLink',
 'videoMeta/subtitleLinks/49/version',
 'videoMeta/subtitleLinks/50/downloadLink',
 'videoMeta/subtitleLinks/50/language',
 'videoMeta/subtitleLinks/50/source',
 'videoMeta/subtitleLinks/50/sourceUnabbreviated',
 'videoMeta/subtitleLinks/50/tiktokLink',
 'videoMeta/subtitleLinks/50/version',
 'videoMeta/subtitleLinks/51/downloadLink',
 'videoMeta/subtitleLinks/51/language',
 'videoMeta/subtitleLinks/51/source',
 'videoMeta/subtitleLinks/51/sourceUnabbreviated',
 'videoMeta/subtitleLinks/51/tiktokLink',
 'videoMeta/subtitleLinks/51/version',
 'videoMeta/subtitleLinks/52/downloadLink',
 'videoMeta/subtitleLinks/52/language',
 'videoMeta/subtitleLinks/52/source',
 'videoMeta/subtitleLinks/52/sourceUnabbreviated',
 'videoMeta/subtitleLinks/52/tiktokLink',
 'videoMeta/subtitleLinks/52/version',
 'videoMeta/subtitleLinks/53/downloadLink',
 'videoMeta/subtitleLinks/53/language',
 'videoMeta/subtitleLinks/53/source',
 'videoMeta/subtitleLinks/53/sourceUnabbreviated',
 'videoMeta/subtitleLinks/53/tiktokLink',
 'videoMeta/subtitleLinks/53/version',
 'videoMeta/subtitleLinks/54/downloadLink',
 'videoMeta/subtitleLinks/54/language',
 'videoMeta/subtitleLinks/54/source',
 'videoMeta/subtitleLinks/54/sourceUnabbreviated',
 'videoMeta/subtitleLinks/54/tiktokLink',
 'videoMeta/subtitleLinks/54/version',
 'videoMeta/subtitleLinks/55/downloadLink',
 'videoMeta/subtitleLinks/55/language',
 'videoMeta/subtitleLinks/55/source',
 'videoMeta/subtitleLinks/55/sourceUnabbreviated',
 'videoMeta/subtitleLinks/55/tiktokLink',
 'videoMeta/subtitleLinks/55/version',
 'videoMeta/subtitleLinks/56/downloadLink',
 'videoMeta/subtitleLinks/56/language',
 'videoMeta/subtitleLinks/56/source',
 'videoMeta/subtitleLinks/56/sourceUnabbreviated',
 'videoMeta/subtitleLinks/56/tiktokLink',
 'videoMeta/subtitleLinks/56/version',
 'videoMeta/subtitleLinks/57/downloadLink',
 'videoMeta/subtitleLinks/57/language',
 'videoMeta/subtitleLinks/57/source',
 'videoMeta/subtitleLinks/57/sourceUnabbreviated',
 'videoMeta/subtitleLinks/57/tiktokLink',
 'videoMeta/subtitleLinks/57/version',
 'videoMeta/subtitleLinks/58/downloadLink',
 'videoMeta/subtitleLinks/58/language',
 'videoMeta/subtitleLinks/58/source',
 'videoMeta/subtitleLinks/58/sourceUnabbreviated',
 'videoMeta/subtitleLinks/58/tiktokLink',
 'videoMeta/subtitleLinks/58/version',
 'videoMeta/subtitleLinks/59/downloadLink',
 'videoMeta/subtitleLinks/59/language',
 'videoMeta/subtitleLinks/59/source',
 'videoMeta/subtitleLinks/59/sourceUnabbreviated',
 'videoMeta/subtitleLinks/59/tiktokLink',
 'videoMeta/subtitleLinks/59/version',
 'videoMeta/subtitleLinks/60/downloadLink',
 'videoMeta/subtitleLinks/60/language',
 'videoMeta/subtitleLinks/60/source',
 'videoMeta/subtitleLinks/60/sourceUnabbreviated',
 'videoMeta/subtitleLinks/60/tiktokLink',
 'videoMeta/subtitleLinks/60/version',
 'videoMeta/subtitleLinks/61/downloadLink',
 'videoMeta/subtitleLinks/61/language',
 'videoMeta/subtitleLinks/61/source',
 'videoMeta/subtitleLinks/61/sourceUnabbreviated',
 'videoMeta/subtitleLinks/61/tiktokLink',
 'videoMeta/subtitleLinks/61/version',
 'videoMeta/subtitleLinks/62/downloadLink',
 'videoMeta/subtitleLinks/62/language',
 'videoMeta/subtitleLinks/62/source',
 'videoMeta/subtitleLinks/62/sourceUnabbreviated',
 'videoMeta/subtitleLinks/62/tiktokLink',
 'videoMeta/subtitleLinks/62/version',
 'videoMeta/width',
 'webVideoUrl',
 'detailedMentions/0/postUrl',
 'videoMeta/subtitleLinks/63/downloadLink',
 'videoMeta/subtitleLinks/63/language',
 'videoMeta/subtitleLinks/63/source',
 'videoMeta/subtitleLinks/63/sourceUnabbreviated',
 'videoMeta/subtitleLinks/63/tiktokLink',
 'videoMeta/subtitleLinks/63/version',
 'videoMeta/subtitleLinks/64/downloadLink',
 'videoMeta/subtitleLinks/64/language',
 'videoMeta/subtitleLinks/64/source',
 'videoMeta/subtitleLinks/64/sourceUnabbreviated',
 'videoMeta/subtitleLinks/64/tiktokLink',
 'videoMeta/subtitleLinks/64/version',
 'videoMeta/subtitleLinks/65/downloadLink',
 'videoMeta/subtitleLinks/65/language',
 'videoMeta/subtitleLinks/65/source',
 'videoMeta/subtitleLinks/65/sourceUnabbreviated',
 'videoMeta/subtitleLinks/65/tiktokLink',
 'videoMeta/subtitleLinks/65/version',
 'videoMeta/subtitleLinks/66/downloadLink',
 'videoMeta/subtitleLinks/66/language',

| Column | Description |
|--------|-------------|
id | ID Number of the video
text| The caption from the video
createTime| The date and time the video was posted (Note POSTED and not TAKEN)
authorMeta.id| ID number of the profile
authorMeta.name| The handle of the profile
authorMeta.nickName| The display name of the profile
authorMeta.verified| If the profile is verified or not
authorMeta.signature| Contents from the bio of a profile
authorMeta.avatar| Full size version of the profile photo (Link will have a quick expiration date)
authorMeta.following| Number of accounts the profile is following
authorMeta.fans| Number of accounts following the profile
authorMeta.heart| Number of likes, in totality, on the profile's posted content
authorMeta.video| Number of videos posted to the profile
authorMeta.digg| Number of videos/comments the user has liked
musicMeta.musicId| ID number for the sound used in a video
musicMeta.musicName| The name of the sound used in a video
musicMeta.musicAuthor| The author of the sound used in a video
musicMeta.musicOriginal| If the sound originated from the user
musicMeta.playUrl| Direct link to the mp3 file of the sound in a video
musicMeta.coverLarge| The biggest version of the cover photo for the sound used in a video (Some links will have a quick expiration date)
musicMeta.duration| The length of the video in seconds
covers.default| Still image of video that is displayed in video feed (Link will have a quick expiration date)
covers.origin| First frame of the video (Link will have a quick expiration date)
covers.dynamic| Short clip of a video (Link will have a quick expiration date)
webVideoUrl| Link to video to include video ID number
videoMeta.height & videoMeta.width| Size of a video
videoMeta.duration| Length of a video
diggCount| Number of likes for a video
shareCount| Number of times a video was shared
playCount| Number of times a video was played
collectCount | Number of saves on a video
commentCount| Number of comments made on the video
mentions| List of user(s) mentioned via @ in text
hashtags| List of hashtag(s) mentioned in text AND the ID number for the respective hashtags
effectStickers| Name and ID number of effect used in a video

In [6]:
df.nunique()

Unnamed: 0                                         1349
authorMeta/avatar                                  7190
authorMeta/bioLink                                    0
authorMeta/digg                                    3440
authorMeta/fans                                    3916
authorMeta/following                               1702
authorMeta/friends                                    1
authorMeta/heart                                   3386
authorMeta/id                                      6074
authorMeta/name                                    6028
authorMeta/nickName                                5903
authorMeta/originalAvatarUrl                       7190
authorMeta/privateAccount                             1
authorMeta/profileUrl                              6028
authorMeta/signature                               5373
authorMeta/verified                                   2
authorMeta/video                                   1789
collectCount                                       3539
commentCount                                       2775
createTime                                         6740
createTimeISO                                      6740
detailedMentions/0/id                               729
detailedMentions/0/name                             707
detailedMentions/0/nickName                         722
detailedMentions/0/profileUrl                       719
detailedMentions/1/id                               153
detailedMentions/1/name                             148
detailedMentions/1/nickName                         151
detailedMentions/1/profileUrl                       151
detailedMentions/2/id                                64
detailedMentions/2/name                              62
detailedMentions/2/nickName                          63
detailedMentions/2/profileUrl                        63
detailedMentions/3/id                                41
detailedMentions/3/name                              39
detailedMentions/3/nickName                          39
detailedMentions/3/profileUrl                        39
detailedMentions/4/id                                21
detailedMentions/4/name                              20
detailedMentions/4/nickName                          20
detailedMentions/4/profileUrl                        20
diggCount                                          3646
effectStickers/0/ID                                 392
effectStickers/0/name                               316
effectStickers/0/stickerStats/useCount                1
effectStickers/1/ID                                 374
effectStickers/1/name                               303
effectStickers/1/stickerStats/useCount                1
effectStickers/2/ID                                 351
effectStickers/2/name                               288
effectStickers/2/stickerStats/useCount                1
effectStickers/3/ID                                 314
effectStickers/3/name                               257
effectStickers/3/stickerStats/useCount                1
effectStickers/4/ID                                 230
effectStickers/4/name                               195
effectStickers/4/stickerStats/useCount                1
effectStickers/5/ID                                 163
effectStickers/5/name                               143
effectStickers/5/stickerStats/useCount                1
effectStickers/6/ID                                 117
effectStickers/6/name                               105
effectStickers/6/stickerStats/useCount                1
effectStickers/7/ID                                  89
effectStickers/7/name                                81
effectStickers/7/stickerStats/useCount                1
effectStickers/8/ID                                  41
effectStickers/8/name                                39
effectStickers/8/stickerStats/useCount                1
hashtags/0/name                                    2450
hashtags/1/name                                    2690
hashtags/2/name                                    2738
hashtags/3/name                                    2543
hashtags/4/name                                    2215
hashtags/5/name                                    1622
hashtags/6/name                                    1339
hashtags/7/name                                    1099
hashtags/8/name                                     923
hashtags/9/name                                     739
hashtags/10/name                                    607
hashtags/11/name                                    492
hashtags/12/name                                    433
hashtags/13/name                                    349
hashtags/14/name                                    303
hashtags/15/name                                    260
hashtags/16/name                                    232
hashtags/17/name                                    194
hashtags/18/name                                    165
hashtags/19/name                                    145
hashtags/20/name                                    118
hashtags/21/name                                    104
id                                                 6763
input                                               104
isAd                                                  2
isPinned                                              1
isSlideshow                                           2
isSponsored                                           2
locationMeta/address                                370
locationMeta/city                                   206
locationMeta/cityCode                               377
locationMeta/countryCode                             47
locationMeta/locationId                             488
locationMeta/locationName                           468
mentions/0                                          722
mentions/1                                          151
mentions/2                                           63
mentions/3                                           39
mentions/4                                           20
musicMeta/coverMediumUrl                           7055
musicMeta/musicAlbum                               1278
musicMeta/musicAuthor                              5411
musicMeta/musicId                                  6127
musicMeta/musicName                                2309
musicMeta/musicOriginal                               2
musicMeta/originalCoverMediumUrl                   7055
musicMeta/playUrl                                  7879
playCount                                          3946
searchHashtag/name                                   91
searchHashtag/views                                 118
shareCount                                         3274
text                                               6392
textLanguage                                         65
videoMeta/coverUrl                                 8242
videoMeta/definition                                  6
videoMeta/duration                                  333
videoMeta/format                                      1
videoMeta/height                                    185
videoMeta/originalCoverUrl                         8242
videoMeta/subtitleLinks/0/downloadLink             4058
videoMeta/subtitleLinks/0/language                   51
videoMeta/subtitleLinks/0/source                      4
videoMeta/subtitleLinks/0/sourceUnabbreviated         3
videoMeta/subtitleLinks/0/tiktokLink               4058
videoMeta/subtitleLinks/0/version                    22
videoMeta/subtitleLinks/1/downloadLink             2265
videoMeta/subtitleLinks/1/language                   52
videoMeta/subtitleLinks/1/source                      4
videoMeta/subtitleLinks/1/sourceUnabbreviated         3
videoMeta/subtitleLinks/1/tiktokLink               2265
videoMeta/subtitleLinks/1/version                    19
videoMeta/subtitleLinks/2/downloadLink             1474
videoMeta/subtitleLinks/2/language                   52
videoMeta/subtitleLinks/2/source                      4
videoMeta/subtitleLinks/2/sourceUnabbreviated         3
videoMeta/subtitleLinks/2/tiktokLink               1474
videoMeta/subtitleLinks/2/version                    19
videoMeta/subtitleLinks/3/downloadLink             1425
videoMeta/subtitleLinks/3/language                   52
videoMeta/subtitleLinks/3/source                      3
videoMeta/subtitleLinks/3/sourceUnabbreviated         3
videoMeta/subtitleLinks/3/tiktokLink               1425
videoMeta/subtitleLinks/3/version                    17
videoMeta/subtitleLinks/4/downloadLink             1398
videoMeta/subtitleLinks/4/language                   52
videoMeta/subtitleLinks/4/source                      2
videoMeta/subtitleLinks/4/sourceUnabbreviated         2
videoMeta/subtitleLinks/4/tiktokLink               1398
videoMeta/subtitleLinks/4/version                    16
videoMeta/subtitleLinks/5/downloadLink             1374
videoMeta/subtitleLinks/5/language                   52
videoMeta/subtitleLinks/5/source                      3
videoMeta/subtitleLinks/5/sourceUnabbreviated         2
videoMeta/subtitleLinks/5/tiktokLink               1374
videoMeta/subtitleLinks/5/version                    15
videoMeta/subtitleLinks/6/downloadLink             1353
videoMeta/subtitleLinks/6/language                   50
videoMeta/subtitleLinks/6/source                      3
videoMeta/subtitleLinks/6/sourceUnabbreviated         3
videoMeta/subtitleLinks/6/tiktokLink               1353
videoMeta/subtitleLinks/6/version                    18
videoMeta/subtitleLinks/7/downloadLink             1335
videoMeta/subtitleLinks/7/language                   52
videoMeta/subtitleLinks/7/source                      2
videoMeta/subtitleLinks/7/sourceUnabbreviated         2
videoMeta/subtitleLinks/7/tiktokLink               1335
videoMeta/subtitleLinks/7/version                    20
videoMeta/subtitleLinks/8/downloadLink             1323
videoMeta/subtitleLinks/8/language                   52
videoMeta/subtitleLinks/8/source                      2
videoMeta/subtitleLinks/8/sourceUnabbreviated         2
videoMeta/subtitleLinks/8/tiktokLink               1323
videoMeta/subtitleLinks/8/version                    15
videoMeta/subtitleLinks/9/downloadLink             1315
videoMeta/subtitleLinks/9/language                   52
videoMeta/subtitleLinks/9/source                      2
videoMeta/subtitleLinks/9/sourceUnabbreviated         2
videoMeta/subtitleLinks/9/tiktokLink               1315
videoMeta/subtitleLinks/9/version                    14
videoMeta/subtitleLinks/10/downloadLink            1309
videoMeta/subtitleLinks/10/language                  51
videoMeta/subtitleLinks/10/source                     2
videoMeta/subtitleLinks/10/sourceUnabbreviated        2
videoMeta/subtitleLinks/10/tiktokLink              1309
videoMeta/subtitleLinks/10/version                   18
videoMeta/subtitleLinks/11/downloadLink            1288
videoMeta/subtitleLinks/11/language                  52
videoMeta/subtitleLinks/11/source                     2
videoMeta/subtitleLinks/11/sourceUnabbreviated        2
videoMeta/subtitleLinks/11/tiktokLink              1288
videoMeta/subtitleLinks/11/version                   16
videoMeta/subtitleLinks/12/downloadLink            1273
videoMeta/subtitleLinks/12/language                  52
videoMeta/subtitleLinks/12/source                     2
videoMeta/subtitleLinks/12/sourceUnabbreviated        2
videoMeta/subtitleLinks/12/tiktokLink              1273
videoMeta/subtitleLinks/12/version                   14
videoMeta/subtitleLinks/13/downloadLink            1203
videoMeta/subtitleLinks/13/language                  52
videoMeta/subtitleLinks/13/source                     2
videoMeta/subtitleLinks/13/sourceUnabbreviated        2
videoMeta/subtitleLinks/13/tiktokLink              1203
videoMeta/subtitleLinks/13/version                   15
videoMeta/subtitleLinks/14/downloadLink            1165
videoMeta/subtitleLinks/14/language                  52
videoMeta/subtitleLinks/14/source                     2
videoMeta/subtitleLinks/14/sourceUnabbreviated        2
videoMeta/subtitleLinks/14/tiktokLink              1165
videoMeta/subtitleLinks/14/version                   14
videoMeta/subtitleLinks/15/downloadLink            1143
videoMeta/subtitleLinks/15/language                  51
videoMeta/subtitleLinks/15/source                     2
videoMeta/subtitleLinks/15/sourceUnabbreviated        2
videoMeta/subtitleLinks/15/tiktokLink              1143
videoMeta/subtitleLinks/15/version                   13
videoMeta/subtitleLinks/16/downloadLink            1128
videoMeta/subtitleLinks/16/language                  52
videoMeta/subtitleLinks/16/source                     2
videoMeta/subtitleLinks/16/sourceUnabbreviated        2
videoMeta/subtitleLinks/16/tiktokLink              1128
videoMeta/subtitleLinks/16/version                   13
videoMeta/subtitleLinks/17/downloadLink            1107
videoMeta/subtitleLinks/17/language                  52
videoMeta/subtitleLinks/17/source                     2
videoMeta/subtitleLinks/17/sourceUnabbreviated        2
videoMeta/subtitleLinks/17/tiktokLink              1107
videoMeta/subtitleLinks/17/version                   17
videoMeta/subtitleLinks/18/downloadLink            1098
videoMeta/subtitleLinks/18/language                  51
videoMeta/subtitleLinks/18/source                     2
videoMeta/subtitleLinks/18/sourceUnabbreviated        2
videoMeta/subtitleLinks/18/tiktokLink              1098
videoMeta/subtitleLinks/18/version                   13
videoMeta/subtitleLinks/19/downloadLink            1086
videoMeta/subtitleLinks/19/language                  52
videoMeta/subtitleLinks/19/source                     2
videoMeta/subtitleLinks/19/sourceUnabbreviated        2
videoMeta/subtitleLinks/19/tiktokLink              1086
videoMeta/subtitleLinks/19/version                   15
videoMeta/subtitleLinks/20/downloadLink            1077
videoMeta/subtitleLinks/20/language                  52
videoMeta/subtitleLinks/20/source                     2
videoMeta/subtitleLinks/20/sourceUnabbreviated        2
videoMeta/subtitleLinks/20/tiktokLink              1077
videoMeta/subtitleLinks/20/version                   13
videoMeta/subtitleLinks/21/downloadLink            1066
videoMeta/subtitleLinks/21/language                  52
videoMeta/subtitleLinks/21/source                     2
videoMeta/subtitleLinks/21/sourceUnabbreviated        2
videoMeta/subtitleLinks/21/tiktokLink              1066
videoMeta/subtitleLinks/21/version                   15
videoMeta/subtitleLinks/22/downloadLink            1060
videoMeta/subtitleLinks/22/language                  52
videoMeta/subtitleLinks/22/source                     2
videoMeta/subtitleLinks/22/sourceUnabbreviated        2
videoMeta/subtitleLinks/22/tiktokLink              1060
videoMeta/subtitleLinks/22/version                   13
videoMeta/subtitleLinks/23/downloadLink            1047
videoMeta/subtitleLinks/23/language                  52
videoMeta/subtitleLinks/23/source                     2
videoMeta/subtitleLinks/23/sourceUnabbreviated        2
videoMeta/subtitleLinks/23/tiktokLink              1047
videoMeta/subtitleLinks/23/version                   11
videoMeta/subtitleLinks/24/downloadLink            1037
videoMeta/subtitleLinks/24/language                  52
videoMeta/subtitleLinks/24/source                     2
videoMeta/subtitleLinks/24/sourceUnabbreviated        2
videoMeta/subtitleLinks/24/tiktokLink              1037
videoMeta/subtitleLinks/24/version                   13
videoMeta/subtitleLinks/25/downloadLink            1025
videoMeta/subtitleLinks/25/language                  50
videoMeta/subtitleLinks/25/source                     2
videoMeta/subtitleLinks/25/sourceUnabbreviated        2
videoMeta/subtitleLinks/25/tiktokLink              1025
videoMeta/subtitleLinks/25/version                   15
videoMeta/subtitleLinks/26/downloadLink            1002
videoMeta/subtitleLinks/26/language                  52
videoMeta/subtitleLinks/26/source                     2
videoMeta/subtitleLinks/26/sourceUnabbreviated        2
videoMeta/subtitleLinks/26/tiktokLink              1002
videoMeta/subtitleLinks/26/version                   14
videoMeta/subtitleLinks/27/downloadLink             995
videoMeta/subtitleLinks/27/language                  51
videoMeta/subtitleLinks/27/source                     2
videoMeta/subtitleLinks/27/sourceUnabbreviated        2
videoMeta/subtitleLinks/27/tiktokLink               995
videoMeta/subtitleLinks/27/version                   13
videoMeta/subtitleLinks/28/downloadLink             974
videoMeta/subtitleLinks/28/language                  51
videoMeta/subtitleLinks/28/source                     2
videoMeta/subtitleLinks/28/sourceUnabbreviated        2
videoMeta/subtitleLinks/28/tiktokLink               974
videoMeta/subtitleLinks/28/version                   14
videoMeta/subtitleLinks/29/downloadLink             954
videoMeta/subtitleLinks/29/language                  51
videoMeta/subtitleLinks/29/source                     2
videoMeta/subtitleLinks/29/sourceUnabbreviated        2
videoMeta/subtitleLinks/29/tiktokLink               954
videoMeta/subtitleLinks/29/version                   13
videoMeta/subtitleLinks/30/downloadLink             946
videoMeta/subtitleLinks/30/language                  52
videoMeta/subtitleLinks/30/source                     2
videoMeta/subtitleLinks/30/sourceUnabbreviated        2
videoMeta/subtitleLinks/30/tiktokLink               946
videoMeta/subtitleLinks/30/version                   11
videoMeta/subtitleLinks/31/downloadLink             931
videoMeta/subtitleLinks/31/language                  51
videoMeta/subtitleLinks/31/source                     2
videoMeta/subtitleLinks/31/sourceUnabbreviated        2
videoMeta/subtitleLinks/31/tiktokLink               931
videoMeta/subtitleLinks/31/version                   13
videoMeta/subtitleLinks/32/downloadLink             911
videoMeta/subtitleLinks/32/language                  52
videoMeta/subtitleLinks/32/source                     2
videoMeta/subtitleLinks/32/sourceUnabbreviated        2
videoMeta/subtitleLinks/32/tiktokLink               911
videoMeta/subtitleLinks/32/version                   13
videoMeta/subtitleLinks/33/downloadLink             900
videoMeta/subtitleLinks/33/language                  52
videoMeta/subtitleLinks/33/source                     2
videoMeta/subtitleLinks/33/sourceUnabbreviated        2
videoMeta/subtitleLinks/33/tiktokLink               900
videoMeta/subtitleLinks/33/version                   12
videoMeta/subtitleLinks/34/downloadLink             890
videoMeta/subtitleLinks/34/language                  52
videoMeta/subtitleLinks/34/source                     2
videoMeta/subtitleLinks/34/sourceUnabbreviated        2
videoMeta/subtitleLinks/34/tiktokLink               890
videoMeta/subtitleLinks/34/version                   10
videoMeta/subtitleLinks/35/downloadLink             874
videoMeta/subtitleLinks/35/language                  51
videoMeta/subtitleLinks/35/source                     2
videoMeta/subtitleLinks/35/sourceUnabbreviated        2
videoMeta/subtitleLinks/35/tiktokLink               874
videoMeta/subtitleLinks/35/version                   14
videoMeta/subtitleLinks/36/downloadLink             844
videoMeta/subtitleLinks/36/language                  52
videoMeta/subtitleLinks/36/source                     2
videoMeta/subtitleLinks/36/sourceUnabbreviated        2
videoMeta/subtitleLinks/36/tiktokLink               844
videoMeta/subtitleLinks/36/version                   11
videoMeta/subtitleLinks/37/downloadLink             830
videoMeta/subtitleLinks/37/language                  52
videoMeta/subtitleLinks/37/source                     2
videoMeta/subtitleLinks/37/sourceUnabbreviated        2
videoMeta/subtitleLinks/37/tiktokLink               830
videoMeta/subtitleLinks/37/version                   13
videoMeta/subtitleLinks/38/downloadLink             804

In [7]:
df.dtypes

Unnamed: 0                                           int64
authorMeta/avatar                                   object
authorMeta/bioLink                                 float64
authorMeta/digg                                    float64
authorMeta/fans                                    float64
authorMeta/following                               float64
authorMeta/friends                                 float64
authorMeta/heart                                   float64
authorMeta/id                                      float64
authorMeta/name                                     object
authorMeta/nickName                                 object
authorMeta/originalAvatarUrl                        object
authorMeta/privateAccount                           object
authorMeta/profileUrl                               object
authorMeta/signature                                object
authorMeta/verified                                 object
authorMeta/video                                   float64
collectCount                                       float64
commentCount                                       float64
createTime                                         float64
createTimeISO                                       object
detailedMentions/0/id                              float64
detailedMentions/0/name                             object
detailedMentions/0/nickName                         object
detailedMentions/0/profileUrl                       object
detailedMentions/1/id                              float64
detailedMentions/1/name                             object
detailedMentions/1/nickName                         object
detailedMentions/1/profileUrl                       object
detailedMentions/2/id                              float64
detailedMentions/2/name                             object
detailedMentions/2/nickName                         object
detailedMentions/2/profileUrl                       object
detailedMentions/3/id                              float64
detailedMentions/3/name                             object
detailedMentions/3/nickName                         object
detailedMentions/3/profileUrl                       object
detailedMentions/4/id                              float64
detailedMentions/4/name                             object
detailedMentions/4/nickName                         object
detailedMentions/4/profileUrl                       object
diggCount                                          float64
effectStickers/0/ID                                float64
effectStickers/0/name                               object
effectStickers/0/stickerStats/useCount             float64
effectStickers/1/ID                                float64
effectStickers/1/name                               object
effectStickers/1/stickerStats/useCount             float64
effectStickers/2/ID                                float64
effectStickers/2/name                               object
effectStickers/2/stickerStats/useCount             float64
effectStickers/3/ID                                float64
effectStickers/3/name                               object
effectStickers/3/stickerStats/useCount             float64
effectStickers/4/ID                                float64
effectStickers/4/name                               object
effectStickers/4/stickerStats/useCount             float64
effectStickers/5/ID                                float64
effectStickers/5/name                               object
effectStickers/5/stickerStats/useCount             float64
effectStickers/6/ID                                float64
effectStickers/6/name                               object
effectStickers/6/stickerStats/useCount             float64
effectStickers/7/ID                                float64
effectStickers/7/name                               object
effectStickers/7/stickerStats/useCount             float64
effectStickers/8/ID                                float64
effectStickers/8/name                               object
effectStickers/8/stickerStats/useCount             float64
hashtags/0/name                                     object
hashtags/1/name                                     object
hashtags/2/name                                     object
hashtags/3/name                                     object
hashtags/4/name                                     object
hashtags/5/name                                     object
hashtags/6/name                                     object
hashtags/7/name                                     object
hashtags/8/name                                     object
hashtags/9/name                                     object
hashtags/10/name                                    object
hashtags/11/name                                    object
hashtags/12/name                                    object
hashtags/13/name                                    object
hashtags/14/name                                    object
hashtags/15/name                                    object
hashtags/16/name                                    object
hashtags/17/name                                    object
hashtags/18/name                                    object
hashtags/19/name                                    object
hashtags/20/name                                    object
hashtags/21/name                                    object
id                                                 float64
input                                               object
isAd                                                object
isPinned                                            object
isSlideshow                                         object
isSponsored                                         object
locationMeta/address                                object
locationMeta/city                                   object
locationMeta/cityCode                              float64
locationMeta/countryCode                           float64
locationMeta/locationId                            float64
locationMeta/locationName                           object
mentions/0                                          object
mentions/1                                          object
mentions/2                                          object
mentions/3                                          object
mentions/4                                          object
musicMeta/coverMediumUrl                            object
musicMeta/musicAlbum                                object
musicMeta/musicAuthor                               object
musicMeta/musicId                                  float64
musicMeta/musicName                                 object
musicMeta/musicOriginal                             object
musicMeta/originalCoverMediumUrl                    object
musicMeta/playUrl                                   object
playCount                                          float64
searchHashtag/name                                  object
searchHashtag/views                                float64
shareCount                                         float64
text                                                object
textLanguage                                        object
videoMeta/coverUrl                                  object
videoMeta/definition                                object
videoMeta/duration                                 float64
videoMeta/format                                    object
videoMeta/height                                   float64
videoMeta/originalCoverUrl                          object
videoMeta/subtitleLinks/0/downloadLink              object
videoMeta/subtitleLinks/0/language                  object
videoMeta/subtitleLinks/0/source                    object
videoMeta/subtitleLinks/0/sourceUnabbreviated       object
videoMeta/subtitleLinks/0/tiktokLink                object
videoMeta/subtitleLinks/0/version                   object
videoMeta/subtitleLinks/1/downloadLink              object
videoMeta/subtitleLinks/1/language                  object
videoMeta/subtitleLinks/1/source                    object
videoMeta/subtitleLinks/1/sourceUnabbreviated       object
videoMeta/subtitleLinks/1/tiktokLink                object
videoMeta/subtitleLinks/1/version                   object
videoMeta/subtitleLinks/2/downloadLink              object
videoMeta/subtitleLinks/2/language                  object
videoMeta/subtitleLinks/2/source                    object
videoMeta/subtitleLinks/2/sourceUnabbreviated       object
videoMeta/subtitleLinks/2/tiktokLink                object
videoMeta/subtitleLinks/2/version                   object
videoMeta/subtitleLinks/3/downloadLink              object
videoMeta/subtitleLinks/3/language                  object
videoMeta/subtitleLinks/3/source                    object
videoMeta/subtitleLinks/3/sourceUnabbreviated       object
videoMeta/subtitleLinks/3/tiktokLink                object
videoMeta/subtitleLinks/3/version                   object
videoMeta/subtitleLinks/4/downloadLink              object
videoMeta/subtitleLinks/4/language                  object
videoMeta/subtitleLinks/4/source                    object
videoMeta/subtitleLinks/4/sourceUnabbreviated       object
videoMeta/subtitleLinks/4/tiktokLink                object
videoMeta/subtitleLinks/4/version                   object
videoMeta/subtitleLinks/5/downloadLink              object
videoMeta/subtitleLinks/5/language                  object
videoMeta/subtitleLinks/5/source                    object
videoMeta/subtitleLinks/5/sourceUnabbreviated       object
videoMeta/subtitleLinks/5/tiktokLink                object
videoMeta/subtitleLinks/5/version                   object
videoMeta/subtitleLinks/6/downloadLink              object
videoMeta/subtitleLinks/6/language                  object
videoMeta/subtitleLinks/6/source                    object
videoMeta/subtitleLinks/6/sourceUnabbreviated       object
videoMeta/subtitleLinks/6/tiktokLink                object
videoMeta/subtitleLinks/6/version                   object
videoMeta/subtitleLinks/7/downloadLink              object
videoMeta/subtitleLinks/7/language                  object
videoMeta/subtitleLinks/7/source                    object
videoMeta/subtitleLinks/7/sourceUnabbreviated       object
videoMeta/subtitleLinks/7/tiktokLink                object
videoMeta/subtitleLinks/7/version                   object
videoMeta/subtitleLinks/8/downloadLink              object
videoMeta/subtitleLinks/8/language                  object
videoMeta/subtitleLinks/8/source                    object
videoMeta/subtitleLinks/8/sourceUnabbreviated       object
videoMeta/subtitleLinks/8/tiktokLink                object
videoMeta/subtitleLinks/8/version                   object
videoMeta/subtitleLinks/9/downloadLink              object
videoMeta/subtitleLinks/9/language                  object
videoMeta/subtitleLinks/9/source                    object
videoMeta/subtitleLinks/9/sourceUnabbreviated       object
videoMeta/subtitleLinks/9/tiktokLink                object
videoMeta/subtitleLinks/9/version                   object
videoMeta/subtitleLinks/10/downloadLink             object
videoMeta/subtitleLinks/10/language                 object
videoMeta/subtitleLinks/10/source                   object
videoMeta/subtitleLinks/10/sourceUnabbreviated      object
videoMeta/subtitleLinks/10/tiktokLink               object
videoMeta/subtitleLinks/10/version                  object
videoMeta/subtitleLinks/11/downloadLink             object
videoMeta/subtitleLinks/11/language                 object
videoMeta/subtitleLinks/11/source                   object
videoMeta/subtitleLinks/11/sourceUnabbreviated      object
videoMeta/subtitleLinks/11/tiktokLink               object
videoMeta/subtitleLinks/11/version                  object
videoMeta/subtitleLinks/12/downloadLink             object
videoMeta/subtitleLinks/12/language                 object
videoMeta/subtitleLinks/12/source                   object
videoMeta/subtitleLinks/12/sourceUnabbreviated      object
videoMeta/subtitleLinks/12/tiktokLink               object
videoMeta/subtitleLinks/12/version                  object
videoMeta/subtitleLinks/13/downloadLink             object
videoMeta/subtitleLinks/13/language                 object
videoMeta/subtitleLinks/13/source                   object
videoMeta/subtitleLinks/13/sourceUnabbreviated      object
videoMeta/subtitleLinks/13/tiktokLink               object
videoMeta/subtitleLinks/13/version                  object
videoMeta/subtitleLinks/14/downloadLink             object
videoMeta/subtitleLinks/14/language                 object
videoMeta/subtitleLinks/14/source                   object
videoMeta/subtitleLinks/14/sourceUnabbreviated      object
videoMeta/subtitleLinks/14/tiktokLink               object
videoMeta/subtitleLinks/14/version                  object
videoMeta/subtitleLinks/15/downloadLink             object
videoMeta/subtitleLinks/15/language                 object
videoMeta/subtitleLinks/15/source                   object
videoMeta/subtitleLinks/15/sourceUnabbreviated      object
videoMeta/subtitleLinks/15/tiktokLink               object
videoMeta/subtitleLinks/15/version                  object
videoMeta/subtitleLinks/16/downloadLink             object
videoMeta/subtitleLinks/16/language                 object
videoMeta/subtitleLinks/16/source                   object
videoMeta/subtitleLinks/16/sourceUnabbreviated      object
videoMeta/subtitleLinks/16/tiktokLink               object
videoMeta/subtitleLinks/16/version                  object
videoMeta/subtitleLinks/17/downloadLink             object
videoMeta/subtitleLinks/17/language                 object
videoMeta/subtitleLinks/17/source                   object
videoMeta/subtitleLinks/17/sourceUnabbreviated      object
videoMeta/subtitleLinks/17/tiktokLink               object
videoMeta/subtitleLinks/17/version                  object
videoMeta/subtitleLinks/18/downloadLink             object
videoMeta/subtitleLinks/18/language                 object
videoMeta/subtitleLinks/18/source                   object
videoMeta/subtitleLinks/18/sourceUnabbreviated      object
videoMeta/subtitleLinks/18/tiktokLink               object
videoMeta/subtitleLinks/18/version                  object
videoMeta/subtitleLinks/19/downloadLink             object
videoMeta/subtitleLinks/19/language                 object
videoMeta/subtitleLinks/19/source                   object
videoMeta/subtitleLinks/19/sourceUnabbreviated      object
videoMeta/subtitleLinks/19/tiktokLink               object
videoMeta/subtitleLinks/19/version                  object
videoMeta/subtitleLinks/20/downloadLink             object
videoMeta/subtitleLinks/20/language                 object
videoMeta/subtitleLinks/20/source                   object
videoMeta/subtitleLinks/20/sourceUnabbreviated      object
videoMeta/subtitleLinks/20/tiktokLink               object
videoMeta/subtitleLinks/20/version                  object
videoMeta/subtitleLinks/21/downloadLink             object
videoMeta/subtitleLinks/21/language                 object
videoMeta/subtitleLinks/21/source                   object
videoMeta/subtitleLinks/21/sourceUnabbreviated      object
videoMeta/subtitleLinks/21/tiktokLink               object
videoMeta/subtitleLinks/21/version                  object
videoMeta/subtitleLinks/22/downloadLink             object
videoMeta/subtitleLinks/22/language                 object
videoMeta/subtitleLinks/22/source                   object
videoMeta/subtitleLinks/22/sourceUnabbreviated      object
videoMeta/subtitleLinks/22/tiktokLink               object
videoMeta/subtitleLinks/22/version                  object
videoMeta/subtitleLinks/23/downloadLink             object
videoMeta/subtitleLinks/23/language                 object
videoMeta/subtitleLinks/23/source                   object
videoMeta/subtitleLinks/23/sourceUnabbreviated      object
videoMeta/subtitleLinks/23/tiktokLink               object
videoMeta/subtitleLinks/23/version                  object
videoMeta/subtitleLinks/24/downloadLink             object
videoMeta/subtitleLinks/24/language                 object
videoMeta/subtitleLinks/24/source                   object
videoMeta/subtitleLinks/24/sourceUnabbreviated      object
videoMeta/subtitleLinks/24/tiktokLink               object
videoMeta/subtitleLinks/24/version                  object
videoMeta/subtitleLinks/25/downloadLink             object
videoMeta/subtitleLinks/25/language                 object
videoMeta/subtitleLinks/25/source                   object
videoMeta/subtitleLinks/25/sourceUnabbreviated      object
videoMeta/subtitleLinks/25/tiktokLink               object
videoMeta/subtitleLinks/25/version                  object
videoMeta/subtitleLinks/26/downloadLink             object
videoMeta/subtitleLinks/26/language                 object
videoMeta/subtitleLinks/26/source                   object
videoMeta/subtitleLinks/26/sourceUnabbreviated      object
videoMeta/subtitleLinks/26/tiktokLink               object
videoMeta/subtitleLinks/26/version                  object
videoMeta/subtitleLinks/27/downloadLink             object
videoMeta/subtitleLinks/27/language                 object
videoMeta/subtitleLinks/27/source                   object
videoMeta/subtitleLinks/27/sourceUnabbreviated      object
videoMeta/subtitleLinks/27/tiktokLink               object
videoMeta/subtitleLinks/27/version                  object
videoMeta/subtitleLinks/28/downloadLink             object
videoMeta/subtitleLinks/28/language                 object
videoMeta/subtitleLinks/28/source                   object
videoMeta/subtitleLinks/28/sourceUnabbreviated      object
videoMeta/subtitleLinks/28/tiktokLink               object
videoMeta/subtitleLinks/28/version                  object
videoMeta/subtitleLinks/29/downloadLink             object
videoMeta/subtitleLinks/29/language                 object
videoMeta/subtitleLinks/29/source                   object
videoMeta/subtitleLinks/29/sourceUnabbreviated      object
videoMeta/subtitleLinks/29/tiktokLink               object
videoMeta/subtitleLinks/29/version                  object
videoMeta/subtitleLinks/30/downloadLink             object
videoMeta/subtitleLinks/30/language                 object
videoMeta/subtitleLinks/30/source                   object
videoMeta/subtitleLinks/30/sourceUnabbreviated      object
videoMeta/subtitleLinks/30/tiktokLink               object
videoMeta/subtitleLinks/30/version                  object
videoMeta/subtitleLinks/31/downloadLink             object
videoMeta/subtitleLinks/31/language                 object
videoMeta/subtitleLinks/31/source                   object
videoMeta/subtitleLinks/31/sourceUnabbreviated      object
videoMeta/subtitleLinks/31/tiktokLink               object
videoMeta/subtitleLinks/31/version                  object
videoMeta/subtitleLinks/32/downloadLink             object
videoMeta/subtitleLinks/32/language                 object
videoMeta/subtitleLinks/32/source                   object
videoMeta/subtitleLinks/32/sourceUnabbreviated      object
videoMeta/subtitleLinks/32/tiktokLink               object
videoMeta/subtitleLinks/32/version                  object
videoMeta/subtitleLinks/33/downloadLink             object
videoMeta/subtitleLinks/33/language                 object
videoMeta/subtitleLinks/33/source                   object
videoMeta/subtitleLinks/33/sourceUnabbreviated      object
videoMeta/subtitleLinks/33/tiktokLink               object
videoMeta/subtitleLinks/33/version                  object
videoMeta/subtitleLinks/34/downloadLink             object
videoMeta/subtitleLinks/34/language                 object
videoMeta/subtitleLinks/34/source                   object
videoMeta/subtitleLinks/34/sourceUnabbreviated      object
videoMeta/subtitleLinks/34/tiktokLink               object
videoMeta/subtitleLinks/34/version                  object

In [8]:
df.isna().sum()

Unnamed: 0                                            0
authorMeta/avatar                                    13
authorMeta/bioLink                                 9232
authorMeta/digg                                      13
authorMeta/fans                                      13
authorMeta/following                                 13
authorMeta/friends                                   13
authorMeta/heart                                     13
authorMeta/id                                        13
authorMeta/name                                      13
authorMeta/nickName                                  13
authorMeta/originalAvatarUrl                         13
authorMeta/privateAccount                            13
authorMeta/profileUrl                                13
authorMeta/signature                               1113
authorMeta/verified                                  13
authorMeta/video                                     13
collectCount                                         13
commentCount                                         13
createTime                                           13
createTimeISO                                        13
detailedMentions/0/id                              8147
detailedMentions/0/name                            8158
detailedMentions/0/nickName                        8146
detailedMentions/0/profileUrl                      8146
detailedMentions/1/id                              9019
detailedMentions/1/name                            9022
detailedMentions/1/nickName                        9019
detailedMentions/1/profileUrl                      9019
detailedMentions/2/id                              9141
detailedMentions/2/name                            9142
detailedMentions/2/nickName                        9141
detailedMentions/2/profileUrl                      9141
detailedMentions/3/id                              9173
detailedMentions/3/name                            9173
detailedMentions/3/nickName                        9173
detailedMentions/3/profileUrl                      9173
detailedMentions/4/id                              9206
detailedMentions/4/name                            9206
detailedMentions/4/nickName                        9206
detailedMentions/4/profileUrl                      9206
diggCount                                            13
effectStickers/0/ID                                1396
effectStickers/0/name                              1396
effectStickers/0/stickerStats/useCount             1396
effectStickers/1/ID                                3331
effectStickers/1/name                              3331
effectStickers/1/stickerStats/useCount             3331
effectStickers/2/ID                                4959
effectStickers/2/name                              4959
effectStickers/2/stickerStats/useCount             4959
effectStickers/3/ID                                6246
effectStickers/3/name                              6246
effectStickers/3/stickerStats/useCount             6246
effectStickers/4/ID                                7289
effectStickers/4/name                              7289
effectStickers/4/stickerStats/useCount             7289
effectStickers/5/ID                                8169
effectStickers/5/name                              8169
effectStickers/5/stickerStats/useCount             8169
effectStickers/6/ID                                8641
effectStickers/6/name                              8641
effectStickers/6/stickerStats/useCount             8641
effectStickers/7/ID                                8837
effectStickers/7/name                              8837
effectStickers/7/stickerStats/useCount             8837
effectStickers/8/ID                                9099
effectStickers/8/name                              9099
effectStickers/8/stickerStats/useCount             9099
hashtags/0/name                                    1542
hashtags/1/name                                    1451
hashtags/2/name                                    1847
hashtags/3/name                                    2795
hashtags/4/name                                    3824
hashtags/5/name                                    5455
hashtags/6/name                                    6273
hashtags/7/name                                    6887
hashtags/8/name                                    7394
hashtags/9/name                                    7798
hashtags/10/name                                   8095
hashtags/11/name                                   8293
hashtags/12/name                                   8461
hashtags/13/name                                   8618
hashtags/14/name                                   8698
hashtags/15/name                                   8788
hashtags/16/name                                   8868
hashtags/17/name                                   8937
hashtags/18/name                                   8968
hashtags/19/name                                   9002
hashtags/20/name                                   9047
hashtags/21/name                                   9062
id                                                   13
input                                                 0
isAd                                                 13
isPinned                                             13
isSlideshow                                          13
isSponsored                                          13
locationMeta/address                               8090
locationMeta/city                                  8784
locationMeta/cityCode                              8095
locationMeta/countryCode                           8090
locationMeta/locationId                            8090
locationMeta/locationName                          8090
mentions/0                                         8146
mentions/1                                         9019
mentions/2                                         9141
mentions/3                                         9173
mentions/4                                         9206
musicMeta/coverMediumUrl                             37
musicMeta/musicAlbum                               6769
musicMeta/musicAuthor                                43
musicMeta/musicId                                    13
musicMeta/musicName                                  22
musicMeta/musicOriginal                              13
musicMeta/originalCoverMediumUrl                     37
musicMeta/playUrl                                   309
playCount                                            13
searchHashtag/name                                   13
searchHashtag/views                                  13
shareCount                                           13
text                                                236
textLanguage                                         18
videoMeta/coverUrl                                   14
videoMeta/definition                                 32
videoMeta/duration                                   13
videoMeta/format                                     32
videoMeta/height                                     13
videoMeta/originalCoverUrl                           14
videoMeta/subtitleLinks/0/downloadLink             5174
videoMeta/subtitleLinks/0/language                 5174
videoMeta/subtitleLinks/0/source                   5174
videoMeta/subtitleLinks/0/sourceUnabbreviated      5188
videoMeta/subtitleLinks/0/tiktokLink               5174
videoMeta/subtitleLinks/0/version                  5174
videoMeta/subtitleLinks/1/downloadLink             6967
videoMeta/subtitleLinks/1/language                 6967
videoMeta/subtitleLinks/1/source                   6967
videoMeta/subtitleLinks/1/sourceUnabbreviated      6993
videoMeta/subtitleLinks/1/tiktokLink               6967
videoMeta/subtitleLinks/1/version                  6967
videoMeta/subtitleLinks/2/downloadLink             7758
videoMeta/subtitleLinks/2/language                 7758
videoMeta/subtitleLinks/2/source                   7758
videoMeta/subtitleLinks/2/sourceUnabbreviated      7759
videoMeta/subtitleLinks/2/tiktokLink               7758
videoMeta/subtitleLinks/2/version                  7758
videoMeta/subtitleLinks/3/downloadLink             7807
videoMeta/subtitleLinks/3/language                 7807
videoMeta/subtitleLinks/3/source                   7807
videoMeta/subtitleLinks/3/sourceUnabbreviated      7807
videoMeta/subtitleLinks/3/tiktokLink               7807
videoMeta/subtitleLinks/3/version                  7807
videoMeta/subtitleLinks/4/downloadLink             7834
videoMeta/subtitleLinks/4/language                 7834
videoMeta/subtitleLinks/4/source                   7834
videoMeta/subtitleLinks/4/sourceUnabbreviated      7834
videoMeta/subtitleLinks/4/tiktokLink               7834
videoMeta/subtitleLinks/4/version                  7834
videoMeta/subtitleLinks/5/downloadLink             7858
videoMeta/subtitleLinks/5/language                 7858
videoMeta/subtitleLinks/5/source                   7858
videoMeta/subtitleLinks/5/sourceUnabbreviated      7859
videoMeta/subtitleLinks/5/tiktokLink               7858
videoMeta/subtitleLinks/5/version                  7858
videoMeta/subtitleLinks/6/downloadLink             7879
videoMeta/subtitleLinks/6/language                 7879
videoMeta/subtitleLinks/6/source                   7879
videoMeta/subtitleLinks/6/sourceUnabbreviated      7879
videoMeta/subtitleLinks/6/tiktokLink               7879
videoMeta/subtitleLinks/6/version                  7879
videoMeta/subtitleLinks/7/downloadLink             7897
videoMeta/subtitleLinks/7/language                 7897
videoMeta/subtitleLinks/7/source                   7897
videoMeta/subtitleLinks/7/sourceUnabbreviated      7897
videoMeta/subtitleLinks/7/tiktokLink               7897
videoMeta/subtitleLinks/7/version                  7897
videoMeta/subtitleLinks/8/downloadLink             7909
videoMeta/subtitleLinks/8/language                 7909
videoMeta/subtitleLinks/8/source                   7909
videoMeta/subtitleLinks/8/sourceUnabbreviated      7909
videoMeta/subtitleLinks/8/tiktokLink               7909
videoMeta/subtitleLinks/8/version                  7909
videoMeta/subtitleLinks/9/downloadLink             7917
videoMeta/subtitleLinks/9/language                 7917
videoMeta/subtitleLinks/9/source                   7917
videoMeta/subtitleLinks/9/sourceUnabbreviated      7917
videoMeta/subtitleLinks/9/tiktokLink               7917
videoMeta/subtitleLinks/9/version                  7917
videoMeta/subtitleLinks/10/downloadLink            7923
videoMeta/subtitleLinks/10/language                7923
videoMeta/subtitleLinks/10/source                  7923
videoMeta/subtitleLinks/10/sourceUnabbreviated     7923
videoMeta/subtitleLinks/10/tiktokLink              7923
videoMeta/subtitleLinks/10/version                 7923
videoMeta/subtitleLinks/11/downloadLink            7944
videoMeta/subtitleLinks/11/language                7944
videoMeta/subtitleLinks/11/source                  7944
videoMeta/subtitleLinks/11/sourceUnabbreviated     7944
videoMeta/subtitleLinks/11/tiktokLink              7944
videoMeta/subtitleLinks/11/version                 7944
videoMeta/subtitleLinks/12/downloadLink            7959
videoMeta/subtitleLinks/12/language                7959
videoMeta/subtitleLinks/12/source                  7959
videoMeta/subtitleLinks/12/sourceUnabbreviated     7959
videoMeta/subtitleLinks/12/tiktokLink              7959
videoMeta/subtitleLinks/12/version                 7959
videoMeta/subtitleLinks/13/downloadLink            8029
videoMeta/subtitleLinks/13/language                8029
videoMeta/subtitleLinks/13/source                  8029
videoMeta/subtitleLinks/13/sourceUnabbreviated     8029
videoMeta/subtitleLinks/13/tiktokLink              8029
videoMeta/subtitleLinks/13/version                 8029
videoMeta/subtitleLinks/14/downloadLink            8067
videoMeta/subtitleLinks/14/language                8067
videoMeta/subtitleLinks/14/source                  8067
videoMeta/subtitleLinks/14/sourceUnabbreviated     8067
videoMeta/subtitleLinks/14/tiktokLink              8067
videoMeta/subtitleLinks/14/version                 8067
videoMeta/subtitleLinks/15/downloadLink            8089
videoMeta/subtitleLinks/15/language                8089
videoMeta/subtitleLinks/15/source                  8089
videoMeta/subtitleLinks/15/sourceUnabbreviated     8089
videoMeta/subtitleLinks/15/tiktokLink              8089
videoMeta/subtitleLinks/15/version                 8089
videoMeta/subtitleLinks/16/downloadLink            8104
videoMeta/subtitleLinks/16/language                8104
videoMeta/subtitleLinks/16/source                  8104
videoMeta/subtitleLinks/16/sourceUnabbreviated     8104
videoMeta/subtitleLinks/16/tiktokLink              8104
videoMeta/subtitleLinks/16/version                 8104
videoMeta/subtitleLinks/17/downloadLink            8125
videoMeta/subtitleLinks/17/language                8125
videoMeta/subtitleLinks/17/source                  8125
videoMeta/subtitleLinks/17/sourceUnabbreviated     8125
videoMeta/subtitleLinks/17/tiktokLink              8125
videoMeta/subtitleLinks/17/version                 8125
videoMeta/subtitleLinks/18/downloadLink            8134
videoMeta/subtitleLinks/18/language                8134
videoMeta/subtitleLinks/18/source                  8134
videoMeta/subtitleLinks/18/sourceUnabbreviated     8134
videoMeta/subtitleLinks/18/tiktokLink              8134
videoMeta/subtitleLinks/18/version                 8134
videoMeta/subtitleLinks/19/downloadLink            8146
videoMeta/subtitleLinks/19/language                8146
videoMeta/subtitleLinks/19/source                  8146
videoMeta/subtitleLinks/19/sourceUnabbreviated     8146
videoMeta/subtitleLinks/19/tiktokLink              8146
videoMeta/subtitleLinks/19/version                 8146
videoMeta/subtitleLinks/20/downloadLink            8155
videoMeta/subtitleLinks/20/language                8155
videoMeta/subtitleLinks/20/source                  8155
videoMeta/subtitleLinks/20/sourceUnabbreviated     8155
videoMeta/subtitleLinks/20/tiktokLink              8155
videoMeta/subtitleLinks/20/version                 8155
videoMeta/subtitleLinks/21/downloadLink            8166
videoMeta/subtitleLinks/21/language                8166
videoMeta/subtitleLinks/21/source                  8166
videoMeta/subtitleLinks/21/sourceUnabbreviated     8166
videoMeta/subtitleLinks/21/tiktokLink              8166
videoMeta/subtitleLinks/21/version                 8166
videoMeta/subtitleLinks/22/downloadLink            8172
videoMeta/subtitleLinks/22/language                8172
videoMeta/subtitleLinks/22/source                  8172
videoMeta/subtitleLinks/22/sourceUnabbreviated     8172
videoMeta/subtitleLinks/22/tiktokLink              8172
videoMeta/subtitleLinks/22/version                 8172
videoMeta/subtitleLinks/23/downloadLink            8185
videoMeta/subtitleLinks/23/language                8185
videoMeta/subtitleLinks/23/source                  8185
videoMeta/subtitleLinks/23/sourceUnabbreviated     8185
videoMeta/subtitleLinks/23/tiktokLink              8185
videoMeta/subtitleLinks/23/version                 8185
videoMeta/subtitleLinks/24/downloadLink            8195
videoMeta/subtitleLinks/24/language                8195
videoMeta/subtitleLinks/24/source                  8195
videoMeta/subtitleLinks/24/sourceUnabbreviated     8195
videoMeta/subtitleLinks/24/tiktokLink              8195
videoMeta/subtitleLinks/24/version                 8195
videoMeta/subtitleLinks/25/downloadLink            8207
videoMeta/subtitleLinks/25/language                8207
videoMeta/subtitleLinks/25/source                  8207
videoMeta/subtitleLinks/25/sourceUnabbreviated     8207
videoMeta/subtitleLinks/25/tiktokLink              8207
videoMeta/subtitleLinks/25/version                 8207
videoMeta/subtitleLinks/26/downloadLink            8230
videoMeta/subtitleLinks/26/language                8230
videoMeta/subtitleLinks/26/source                  8230
videoMeta/subtitleLinks/26/sourceUnabbreviated     8230
videoMeta/subtitleLinks/26/tiktokLink              8230
videoMeta/subtitleLinks/26/version                 8230
videoMeta/subtitleLinks/27/downloadLink            8237
videoMeta/subtitleLinks/27/language                8237
videoMeta/subtitleLinks/27/source                  8237
videoMeta/subtitleLinks/27/sourceUnabbreviated     8237
videoMeta/subtitleLinks/27/tiktokLink              8237
videoMeta/subtitleLinks/27/version                 8237
videoMeta/subtitleLinks/28/downloadLink            8258
videoMeta/subtitleLinks/28/language                8258
videoMeta/subtitleLinks/28/source                  8258
videoMeta/subtitleLinks/28/sourceUnabbreviated     8258
videoMeta/subtitleLinks/28/tiktokLink              8258
videoMeta/subtitleLinks/28/version                 8258
videoMeta/subtitleLinks/29/downloadLink            8278
videoMeta/subtitleLinks/29/language                8278
videoMeta/subtitleLinks/29/source                  8278
videoMeta/subtitleLinks/29/sourceUnabbreviated     8278
videoMeta/subtitleLinks/29/tiktokLink              8278
videoMeta/subtitleLinks/29/version                 8278
videoMeta/subtitleLinks/30/downloadLink            8286
videoMeta/subtitleLinks/30/language                8286
videoMeta/subtitleLinks/30/source                  8286
videoMeta/subtitleLinks/30/sourceUnabbreviated     8286
videoMeta/subtitleLinks/30/tiktokLink              8286
videoMeta/subtitleLinks/30/version                 8286
videoMeta/subtitleLinks/31/downloadLink            8301
videoMeta/subtitleLinks/31/language                8301
videoMeta/subtitleLinks/31/source                  8301
videoMeta/subtitleLinks/31/sourceUnabbreviated     8301
videoMeta/subtitleLinks/31/tiktokLink              8301
videoMeta/subtitleLinks/31/version                 8301
videoMeta/subtitleLinks/32/downloadLink            8321
videoMeta/subtitleLinks/32/language                8321
videoMeta/subtitleLinks/32/source                  8321
videoMeta/subtitleLinks/32/sourceUnabbreviated     8321
videoMeta/subtitleLinks/32/tiktokLink              8321
videoMeta/subtitleLinks/32/version                 8321
videoMeta/subtitleLinks/33/downloadLink            8332
videoMeta/subtitleLinks/33/language                8332
videoMeta/subtitleLinks/33/source                  8332
videoMeta/subtitleLinks/33/sourceUnabbreviated     8332
videoMeta/subtitleLinks/33/tiktokLink              8332
videoMeta/subtitleLinks/33/version                 8332
videoMeta/subtitleLinks/34/downloadLink            8342
videoMeta/subtitleLinks/34/language                8342
videoMeta/subtitleLinks/34/source                  8342
videoMeta/subtitleLinks/34/sourceUnabbreviated     8342
videoMeta/subtitleLinks/34/tiktokLink              8342
videoMeta/subtitleLinks/34/version                 8342
videoMeta/subtitleLinks/35/downloadLink            8358
videoMeta/subtitleLinks/35/language                8358
videoMeta/subtitleLinks/35/source                  8358
videoMeta/subtitleLinks/35/sourceUnabbreviated     8358
videoMeta/subtitleLinks/35/tiktokLink              8358
videoMeta/subtitleLinks/35/version                 8358
videoMeta/subtitleLinks/36/downloadLink            8388
videoMeta/subtitleLinks/36/language                8388
videoMeta/subtitleLinks/36/source                  8388
videoMeta/subtitleLinks/36/sourceUnabbreviated     8388
videoMeta/subtitleLinks/36/tiktokLink              8388
videoMeta/subtitleLinks/36/version                 8388
videoMeta/subtitleLinks/37/downloadLink            8402
videoMeta/subtitleLinks/37/language                8402
videoMeta/subtitleLinks/37/source                  8402
videoMeta/subtitleLinks/37/sourceUnabbreviated     8402
videoMeta/subtitleLinks/37/tiktokLink              8402
videoMeta/subtitleLinks/37/version                 8402
videoMeta/subtitleLinks/38/downloadLink            8428

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
columns_to_drop = df.filter(regex='^effectStickers').columns
columns_to_drop_2 = df.filter(regex='^videoMeta/subtitleLinks').columns
columns_to_drop_3 = ['videoMeta/coverUrl', 'videoMeta/height', 'videoMeta/originalCoverUrl', 'videoMeta/width', 'createTimeISO', 'Unnamed: 0']
columns_to_drop_4 = df.filter(regex='^detailedMentions').columns
columns_to_drop_5 = df.filter(regex='^mentions').columns
columns_to_drop_6 = ['authorMeta/avatar', 'authorMeta/originalAvatarUrl', 'authorMeta/bioLink', 'authorMeta/friends', 'authorMeta/privateAccount', 'isPinned']
columns_to_drop_7 = df.filter(regex='^slideshowImageLinks').columns
df_cleaned = df.drop(columns=columns_to_drop)
df_cleaned = df_cleaned.drop(columns=columns_to_drop_2)
df_cleaned = df_cleaned.drop(columns=columns_to_drop_3)
df_cleaned = df_cleaned.drop(columns=columns_to_drop_4)
df_cleaned = df_cleaned.drop(columns=columns_to_drop_5)
df_cleaned = df_cleaned.drop(columns=columns_to_drop_6)
df_cleaned = df_cleaned.drop(columns=columns_to_drop_7)

hashtag_columns = [col for col in df_cleaned.columns if 'hashtags' in col]
df_cleaned['hashtags'] = df_cleaned[hashtag_columns].apply(lambda row: [x for x in row if pd.notna(x)], axis=1)
df_cleaned = df_cleaned.drop(columns=hashtag_columns)

df_cleaned.shape

(9232, 49)

In [11]:
df_cleaned.head()

,authorMeta/digg,authorMeta/fans,authorMeta/following,authorMeta/heart,authorMeta/id,authorMeta/name,authorMeta/nickName,authorMeta/profileUrl,authorMeta/signature,authorMeta/verified,authorMeta/video,collectCount,commentCount,createTime,diggCount,id,input,isAd,isSlideshow,isSponsored,locationMeta/address,locationMeta/city,locationMeta/cityCode,locationMeta/countryCode,locationMeta/locationId,locationMeta/locationName,musicMeta/coverMediumUrl,musicMeta/musicAlbum,musicMeta/musicAuthor,musicMeta/musicId,musicMeta/musicName,musicMeta/musicOriginal,musicMeta/originalCoverMediumUrl,musicMeta/playUrl,playCount,searchHashtag/name,searchHashtag/views,shareCount,text,textLanguage,videoMeta/definition,videoMeta/duration,videoMeta/format,webVideoUrl,authorMeta/roomId,isMuted,error,url,hashtags
0,29.0,135300.0,1.0,101700000.0,7.25e+18,snowfauu,Snowfauuu,https://www.tiktok.com/@snowfauu,r.x1511r@gmail.com FOR PROMO\n\n#signed/ https...,False,908.0,979.0,42.0,1756126218.0,17700.0,7.54e+18,fyp,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,https://p16-sign-sg.tiktokcdn.com/tos-alisg-av...,NaN,🇹🇷,7.29e+18,original sound,True,https://p16-sign-sg.tiktokcdn.com/tos-alisg-av...,https://v77.tiktokcdn-eu.com/4811b5acc13448ced...,117900.0,fyp,99300000000000.0,4465.0,#foryouu #foryoupagе #fyp top from @In Print W...,en,540p,6.0,mp4,https://www.tiktok.com/@snowfauu/video/7542504...,NaN,NaN,NaN,NaN,"[foryouu, foryoupagе, fyp]"
1,205900.0,1470.0,147.0,208700.0,6.89e+18,ayliin.erl,ay,https://www.tiktok.com/@ayliin.erl,free palestine,False,4.0,4499.0,74.0,1756061598.0,80400.0,7.54e+18,fyp,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,https://p16-sign-va.tiktokcdn.com/tos-maliva-a...,NaN,🎀🎀,7.35e+18,original sound,True,https://p16-sign-va.tiktokcdn.com/tos-maliva-a...,https://v77.tiktokcdn-eu.com/6044d1dad9797208b...,363800.0,fyp,99300000000000.0,3453.0,#fyp #fy #flowers,un,540p,11.0,mp4,https://www.tiktok.com/@ayliin.erl/video/75422...,NaN,NaN,NaN,NaN,"[fyp, fy, flowers]"
2,2334.0,152800.0,8.0,850300.0,7.49e+18,heavenly_goals,heavenly_goals,https://www.tiktok.com/@heavenly_goals,"In the beginning was the word, and the word wa...",False,186.0,3645.0,8549.0,1756052840.0,35200.0,7.54e+18,fyp,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,https://p16-sg.tiktokcdn.com/aweme/200x200/tos...,NaN,MoppySound,6.82e+18,Ambient-style emotional piano,False,https://p16-sg.tiktokcdn.com/aweme/200x200/tos...,https://sf19-ies-music-sg.tiktokcdn.com/obj/to...,220200.0,fyp,99300000000000.0,6474.0,Wow Amazing \n#usa #usa_tiktok #tiktokusa #vir...,un,480p,61.0,mp4,https://www.tiktok.com/@heavenly_goals/video/7...,NaN,NaN,NaN,NaN,"[usa, usa_tiktok, tiktokusa, viralvideos, jesu..."
3,159600.0,1372.0,1863.0,71200.0,6.87e+18,zahidghouri99,ZAHID GHOURI,https://www.tiktok.com/@zahidghouri99,BE TRUST ON ALLAH NOTHING ELSE 💓,False,411.0,812.0,63.0,1756120078.0,30100.0,7.54e+18,fyp,False,False,False,"Punjab, Pakistan",Bahawalpur,1183880.0,1168579.0,2.25e+16,Rahim Yar Khan,https://p16-sg.tiktokcdn.com/aweme/200x200/tos...,NaN,𝐒𝐇𝐄𝐑𝐘 𝐄𝐃𝐈𝐓𝐙⚡,7.54e+18,original sound - 𝐒𝐇𝐄𝐑𝐘 𝐄𝐃𝐈𝐓𝐙⚡,False,https://p16-sg.tiktokcdn.com/aweme/200x200/tos...,https://v77.tiktokcdn-eu.com/808abd3272243aacc...,215100.0,fyp,99300000000000.0,208.0,NaN,un,540p,13.0,mp4,https://www.tiktok.com/@zahidghouri99/video/75...,NaN,NaN,NaN,NaN,[]
4,6450.0,1600000.0,285.0,13700000.0,7.14e+18,kionthegreat1_,Kion@funny,https://www.tiktok.com/@kionthegreat1_,Content Creator 🎬\nComedy & Lifestyle \nCollab...,False,970.0,15800.0,11800.0,1755884106.0,326200.0,7.54e+18,fyp,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,https://p16-sg.tiktokcdn.com/aweme/200x200/tos...,Jerusalema,Master KG,6.85e+18,Jerusalema (feat. Nomcebo Zikode),False,https://p16-sg.tiktokcdn.com/aweme/200x200/tos...,https://sf16-ies-music-sg.tiktokcdn.com/obj/to...,20200000.0,fyp,99300000000000.0,48000.0,Human is human #socialexperiment #positive #ff...,en,540p,32.0,mp4,https://www.tiktok.com/@kionthegreat1_/video/7...,NaN,NaN,NaN,NaN,"[socialexperiment, positive, ffyp, forpage, fo..."

In [12]:
df_cleaned.iloc[:,:-1].nunique() # does not include 'hashtags' column which contains list

authorMeta/digg                     3440
authorMeta/fans                     3916
authorMeta/following                1702
authorMeta/heart                    3386
authorMeta/id                       6074
authorMeta/name                     6028
authorMeta/nickName                 5903
authorMeta/profileUrl               6028
authorMeta/signature                5373
authorMeta/verified                    2
authorMeta/video                    1789
collectCount                        3539
commentCount                        2775
createTime                          6740
diggCount                           3646
id                                  6763
input                                104
isAd                                   2
isSlideshow                            2
isSponsored                            2
locationMeta/address                 370
locationMeta/city                    206
locationMeta/cityCode                377
locationMeta/countryCode              47
locationMeta/locationId              488
locationMeta/locationName            468
musicMeta/coverMediumUrl            7055
musicMeta/musicAlbum                1278
musicMeta/musicAuthor               5411
musicMeta/musicId                   6127
musicMeta/musicName                 2309
musicMeta/musicOriginal                2
musicMeta/originalCoverMediumUrl    7055
musicMeta/playUrl                   7879
playCount                           3946
searchHashtag/name                    91
searchHashtag/views                  118
shareCount                          3274
text                                6392
textLanguage                          65
videoMeta/definition                   6
videoMeta/duration                   333
videoMeta/format                       1
webVideoUrl                         6749
authorMeta/roomId                     21
isMuted                                1
error                                  1
url                                   13
dtype: int64

In [13]:
df_cleaned.columns

Index(['authorMeta/digg', 'authorMeta/fans', 'authorMeta/following',
       'authorMeta/heart', 'authorMeta/id', 'authorMeta/name',
       'authorMeta/nickName', 'authorMeta/profileUrl', 'authorMeta/signature',
       'authorMeta/verified', 'authorMeta/video', 'collectCount',
       'commentCount', 'createTime', 'diggCount', 'id', 'input', 'isAd',
       'isSlideshow', 'isSponsored', 'locationMeta/address',
       'locationMeta/city', 'locationMeta/cityCode',
       'locationMeta/countryCode', 'locationMeta/locationId',
       'locationMeta/locationName', 'musicMeta/coverMediumUrl',
       'musicMeta/musicAlbum', 'musicMeta/musicAuthor', 'musicMeta/musicId',
       'musicMeta/musicName', 'musicMeta/musicOriginal',
       'musicMeta/originalCoverMediumUrl', 'musicMeta/playUrl', 'playCount',
       'searchHashtag/name', 'searchHashtag/views', 'shareCount', 'text',
       'textLanguage', 'videoMeta/definition', 'videoMeta/duration',
       'videoMeta/format', 'webVideoUrl', 'authorMeta/roomId', 'isMuted',
       'error', 'url', 'hashtags'],
      dtype='object')

In [14]:
df_cleaned.isna().sum()

authorMeta/digg                       13
authorMeta/fans                       13
authorMeta/following                  13
authorMeta/heart                      13
authorMeta/id                         13
authorMeta/name                       13
authorMeta/nickName                   13
authorMeta/profileUrl                 13
authorMeta/signature                1113
authorMeta/verified                   13
authorMeta/video                      13
collectCount                          13
commentCount                          13
createTime                            13
diggCount                             13
id                                    13
input                                  0
isAd                                  13
isSlideshow                           13
isSponsored                           13
locationMeta/address                8090
locationMeta/city                   8784
locationMeta/cityCode               8095
locationMeta/countryCode            8090
locationMeta/locationId             8090
locationMeta/locationName           8090
musicMeta/coverMediumUrl              37
musicMeta/musicAlbum                6769
musicMeta/musicAuthor                 43
musicMeta/musicId                     13
musicMeta/musicName                   22
musicMeta/musicOriginal               13
musicMeta/originalCoverMediumUrl      37
musicMeta/playUrl                    309
playCount                             13
searchHashtag/name                    13
searchHashtag/views                   13
shareCount                            13
text                                 236
textLanguage                          18
videoMeta/definition                  32
videoMeta/duration                    13
videoMeta/format                      32
webVideoUrl                           13
authorMeta/roomId                   9197
isMuted                             9217
error                               9219
url                                 9219
hashtags                               0
dtype: int64

In [15]:
df_cleaned = df_cleaned[df_cleaned['error'].isna()]
df_cleaned = df_cleaned.drop('error', axis=1)
df_cleaned.shape

(9219, 48)

In [16]:
df_cleaned = df_cleaned[df_cleaned['authorMeta/fans'] != 0]
df_cleaned['viewsPerFollowers'] = df_cleaned['playCount']/df_cleaned['authorMeta/fans']
df_cleaned['likesPerFollowers'] = df_cleaned['diggCount']/df_cleaned['authorMeta/fans']
df_cleaned['commentsPerFollowers'] = df_cleaned['commentCount']/df_cleaned['authorMeta/fans']
df_cleaned['sharesPerFollowers'] = df_cleaned['shareCount']/df_cleaned['authorMeta/fans']
df_cleaned['savesPerFollowers'] = df_cleaned['collectCount']/df_cleaned['authorMeta/fans']

df_cleaned[['viewsPerFollowers', 'likesPerFollowers', 'commentsPerFollowers', 'sharesPerFollowers', 'savesPerFollowers']]

viewsPerFollowers_mean = df_cleaned['viewsPerFollowers'].mean(axis=0)
likesPerFollowers_mean = df_cleaned['likesPerFollowers'].mean(axis=0)
commentsPerFollowers_mean = df_cleaned['commentsPerFollowers'].mean(axis=0)
sharesPerFollowers_mean = df_cleaned['sharesPerFollowers'].mean(axis=0)
savesPerFollowers_mean = df_cleaned['savesPerFollowers'].mean(axis=0)
followers_mean = df_cleaned['authorMeta/fans'].mean(axis=0)

print(f'viewsPerFollowers_mean: {viewsPerFollowers_mean}')
print(f'likesPerFollowers_mean: {likesPerFollowers_mean}')
print(f'commentsPerFollowers_mean: {commentsPerFollowers_mean}')
print(f'sharesPerFollowers_mean: {sharesPerFollowers_mean}')
print(f'savesPerFollowers_mean: {savesPerFollowers_mean}')
print(f'followers mean: {followers_mean}')

viewsPerFollowers_mean: 205.99187887014202
likesPerFollowers_mean: 22.838732379297248
commentsPerFollowers_mean: 0.19830376381318196
sharesPerFollowers_mean: 3.05988236518502
savesPerFollowers_mean: 2.2424637357038963
followers mean: 1328038.3233618233

In [17]:
df_cleaned.to_csv('df_cleaned.csv')